/* Generated by tools/design/gen_trust.mjs from public/trust-security/Section.svg. Do not hand-edit. */

type Props = { className?: string };

/* Card 1 — eye; design box x 203.4..324.6, y 395.8..492.2. */
export const IconReadOnly = ({ className }: Props) => (
<svg width="121.184" height="96.37" viewBox="203.408 395.815 121.184 96.37" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint0_linear_151_3464" x1="324.592" y1="419.908" x2="254.229" y2="419.908" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint1_linear_151_3464" x1="203.408" y1="468.093" x2="273.771" y2="468.093" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint2_linear_151_3464" x1="272.656" y1="451.879" x2="257.385" y2="435.246" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
<linearGradient id="paint3_linear_151_3464" x1="203.408" y1="419.908" x2="273.773" y2="419.908" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint4_linear_151_3464" x1="324.592" y1="468.093" x2="254.227" y2="468.093" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
  </defs>
  <path opacity="0.8" d="M263.998 395.815C292.387 395.815 316.564 414.577 323.604 440.378L324.592 444H306.759L306.085 442.087C300.167 425.312 283.694 413.046 263.998 413.046C261.786 413.046 259.615 413.202 257.495 413.5L254.229 413.959V396.514L256.771 396.224C259.144 395.953 261.556 395.815 263.998 395.815Z" fill="url(#paint0_linear_151_3464)"/>
  <path opacity="0.8" d="M264.002 492.185C235.613 492.185 211.436 473.423 204.396 447.622L203.408 444H221.241L221.915 445.914C227.833 462.688 244.306 474.954 264.002 474.954C266.214 474.954 268.385 474.798 270.505 474.5L273.771 474.041V491.486L271.229 491.776C268.856 492.047 266.444 492.185 264.002 492.185Z" fill="url(#paint1_linear_151_3464)"/>
  <circle opacity="0.8" cx="263.999" cy="444" r="14.0069" fill="url(#paint2_linear_151_3464)"/>
  <path opacity="0.8" fillRule="evenodd" clipRule="evenodd" d="M264.001 395.815C266.444 395.815 268.857 395.953 271.23 396.224L273.773 396.514V413.959L270.505 413.5C268.385 413.202 266.213 413.046 264.001 413.046C244.305 413.046 227.832 425.312 221.915 442.087L221.24 444H203.408L204.396 440.378C211.435 414.577 235.612 395.815 264.001 395.815Z" fill="url(#paint3_linear_151_3464)"/>
  <path opacity="0.8" fillRule="evenodd" clipRule="evenodd" d="M263.999 492.185C261.556 492.185 259.143 492.047 256.77 491.776L254.227 491.486V474.041L257.495 474.5C259.615 474.798 261.787 474.954 263.999 474.954C283.695 474.954 300.168 462.688 306.085 445.914L306.76 444H324.592L323.604 447.622C316.565 473.423 292.388 492.185 263.999 492.185Z" fill="url(#paint4_linear_151_3464)"/>
</svg>
);

/* Card 2 — padlock; design box x 517.8..618.2, y 385.8..502.2. */
export const IconEncryption = ({ className }: Props) => (
<svg width="100.462" height="116.41" viewBox="517.77 385.795 100.462 116.41" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint5_linear_151_3464" x1="599.739" y1="409.656" x2="536.262" y2="409.656" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint6_linear_151_3464" x1="618.232" y1="473.058" x2="517.77" y2="473.058" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint7_linear_151_3464" x1="517.77" y1="436.429" x2="618.207" y2="435.152" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint8_linear_151_3464" x1="572.92" y1="464.375" x2="564.242" y2="454.924" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
  </defs>
  <path opacity="0.8" d="M568.001 385.795C585.53 385.795 599.739 400.006 599.739 417.534V433.517H583.814V417.534C583.814 408.801 576.734 401.721 568.001 401.721C559.267 401.721 552.188 408.801 552.188 417.534V433.517H536.262V417.534C536.262 400.006 550.472 385.795 568.001 385.795Z" fill="url(#paint5_linear_151_3464)"/>
  <path opacity="0.8" d="M618.232 459.898H602.232V486.205H533.77V443.912H517.77V502.205H618.232V459.898Z" fill="url(#paint6_linear_151_3464)"/>
  <path opacity="0.8" d="M517.77 459.898H533.77V433.591H602.232V475.884H618.232V417.591H517.77V459.898Z" fill="url(#paint7_linear_151_3464)"/>
  <rect opacity="0.8" x="560.041" y="451.939" width="15.9185" height="15.9185" fill="url(#paint8_linear_151_3464)"/>
</svg>
);

/* Card 3 — barred ring; design box x 813.9..930.1, y 385.9..502.1. */
export const IconNoTraining = ({ className }: Props) => (
<svg width="116.236" height="116.236" viewBox="813.882 385.882 116.236 116.236" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint9_linear_151_3464" x1="907.238" y1="476.07" x2="845.077" y2="408.366" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
<linearGradient id="paint10_linear_151_3464" x1="912.385" y1="478.05" x2="839.534" y2="407.575" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint11_linear_151_3464" x1="831.644" y1="484.006" x2="912.647" y2="403.005" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
  </defs>
  <path opacity="0.8" d="M929.014 444C929.014 455.276 925.67 466.299 919.405 475.675C913.14 485.051 904.236 492.359 893.818 496.674C883.4 500.989 871.937 502.118 860.877 499.918C849.818 497.718 839.659 492.288 831.685 484.315C823.712 476.341 818.282 466.182 816.082 455.123C813.882 444.063 815.011 432.6 819.326 422.182C823.641 411.764 830.949 402.86 840.325 396.595C849.701 390.33 860.724 386.986 872 386.986V406.371C864.558 406.371 857.283 408.578 851.094 412.713C844.906 416.847 840.083 422.724 837.235 429.6C834.387 436.476 833.642 444.042 835.094 451.341C836.546 458.64 840.13 465.345 845.392 470.608C850.655 475.87 857.36 479.454 864.659 480.906C871.958 482.358 879.524 481.613 886.4 478.765C893.276 475.917 899.153 471.094 903.287 464.906C907.422 458.718 909.629 451.442 909.629 444H929.014Z" fill="url(#paint9_linear_151_3464)"/>
  <path opacity="0.8" d="M814.986 444C814.986 432.724 818.33 421.701 824.595 412.325C830.86 402.949 839.764 395.641 850.182 391.326C860.6 387.011 872.063 385.882 883.123 388.082C894.182 390.282 904.341 395.712 912.315 403.685C920.288 411.659 925.718 421.818 927.918 432.877C930.118 443.937 928.989 455.4 924.674 465.818C920.359 476.236 913.051 485.14 903.675 491.405C894.299 497.67 883.276 501.014 872 501.014V481.629C879.442 481.629 886.717 479.422 892.906 475.287C899.094 471.153 903.917 465.276 906.765 458.4C909.613 451.524 910.358 443.958 908.906 436.659C907.454 429.36 903.87 422.655 898.608 417.392C893.345 412.13 886.64 408.546 879.341 407.094C872.042 405.642 864.476 406.387 857.6 409.235C850.724 412.083 844.847 416.906 840.713 423.094C836.578 429.282 834.371 436.558 834.371 444H814.986Z" fill="url(#paint10_linear_151_3464)"/>
  <path opacity="0.8" d="M904.076 396.867C907.016 398.868 909.776 401.147 912.314 403.686C914.843 406.215 917.115 408.964 919.11 411.892L839.891 491.109C836.964 489.114 834.214 486.843 831.686 484.315C829.147 481.776 826.868 479.016 824.867 476.076L904.076 396.867Z" fill="url(#paint11_linear_151_3464)"/>
</svg>
);

/* Card 4 — person; design box x 1123..1229, y 388.8..499.2. */
export const IconHumanCall = ({ className }: Props) => (
<svg width="106.05" height="110.494" viewBox="1122.97 388.753 106.05 110.494" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint12_linear_151_3464" x1="1150.02" y1="447.614" x2="1204.74" y2="392.9" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint13_linear_151_3464" x1="1138.44" y1="448.891" x2="1174.4" y2="507.402" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint14_linear_151_3464" x1="1124.43" y1="490.65" x2="1134.87" y2="459.296" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
  </defs>
  <path opacity="0.8" fillRule="evenodd" clipRule="evenodd" d="M1177.27 388.753C1194.85 388.753 1209.1 403.004 1209.1 420.583C1209.1 438.162 1194.85 452.413 1177.27 452.413C1159.69 452.412 1145.44 438.162 1145.44 420.583C1145.44 403.004 1159.69 388.753 1177.27 388.753ZM1177.27 404.935C1168.63 404.935 1161.62 411.941 1161.62 420.583C1161.62 429.225 1168.63 436.231 1177.27 436.231C1185.92 436.231 1192.92 429.225 1192.92 420.583C1192.92 411.941 1185.92 404.935 1177.27 404.935Z" fill="url(#paint12_linear_151_3464)"/>
  <path opacity="0.8" d="M1229.01 499.247H1212.83V489.217H1212.84C1212.84 468.87 1196.35 452.374 1176 452.374C1155.65 452.374 1139.16 468.87 1139.16 489.217V499.247H1122.97V489.217C1122.97 459.933 1146.71 436.193 1176 436.193C1205.28 436.193 1229.02 459.933 1229.02 489.217H1229.01V499.247Z" fill="url(#paint13_linear_151_3464)"/>
  <path opacity="0.8" d="M1228.54 482.054C1228.86 484.352 1229.02 486.697 1229.02 489.079V489.217H1229.02V499.226L1229.02 499.244V499.246H1122.98V489.217C1122.98 486.788 1123.14 484.397 1123.46 482.054H1228.54Z" fill="url(#paint14_linear_151_3464)"/>
</svg>
);
