/* Generated by tools/design/gen_trust.mjs from public/trust-security/{Section-1,Section-2}.svg. Do not hand-edit. */

type Props = { className?: string };

/* Label 01 — spanner and screwdriver, 24x24 on a 2 stroke. */
export const GlyphTools = ({ className }: Props) => (
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <path d="M6 6L10.5 10.5M6 6H3L2 3L3 2L6 3V6ZM19.26 2.741L16.63 5.369C16.24 5.765 16.04 5.963 15.96 6.191C15.9 6.392 15.9 6.608 15.96 6.809C16.04 7.037 16.24 7.235 16.63 7.631L16.87 7.869C17.26 8.265 17.46 8.463 17.69 8.537C17.89 8.602 18.11 8.602 18.31 8.537C18.54 8.463 18.74 8.265 19.13 7.869L21.59 5.411C21.85 6.055 22 6.76 22 7.5C22 10.537 19.54 13 16.5 13C16.13 13 15.78 12.964 15.43 12.896C14.94 12.8 14.7 12.752 14.55 12.767C14.4 12.782 14.32 12.806 14.18 12.88C14.05 12.95 13.92 13.081 13.66 13.343L6.5 20.5C5.67 21.328 4.33 21.328 3.5 20.5C2.67 19.671 2.67 18.328 3.5 17.5L10.66 10.343C10.92 10.081 11.05 9.95 11.12 9.819C11.19 9.681 11.22 9.603 11.23 9.447C11.25 9.299 11.2 9.056 11.1 8.57C11.04 8.224 11 7.866 11 7.5C11 4.462 13.46 2 16.5 2C17.51 2 18.45 2.27 19.26 2.741ZM12 15L17.5 20.5C18.33 21.328 19.67 21.328 20.5 20.5C21.33 19.671 21.33 18.328 20.5 17.5L15.98 12.975C15.66 12.945 15.34 12.887 15.04 12.804C14.65 12.697 14.22 12.775 13.94 13.06L12 15Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
</svg>
);

/* Label 02 — ticked shield, 24x24 on a 2 stroke. */
export const GlyphShieldTick = ({ className }: Props) => (
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <path d="M9 11.5L11 13.5L15.5 9M20 12C20 16.908 14.646 20.478 12.698 21.615C12.477 21.744 12.366 21.809 12.21 21.842C12.088 21.868 11.912 21.868 11.79 21.842C11.634 21.809 11.523 21.744 11.302 21.615C9.354 20.478 4 16.908 4 12V7.218C4 6.418 4 6.018 4.131 5.675C4.246 5.371 4.434 5.1 4.678 4.886C4.953 4.642 5.328 4.502 6.076 4.221L11.438 2.211C11.646 2.133 11.75 2.094 11.857 2.078C11.952 2.065 12.048 2.065 12.143 2.078C12.25 2.094 12.354 2.133 12.562 2.211L17.924 4.221C18.672 4.502 19.047 4.642 19.322 4.886C19.566 5.1 19.754 5.371 19.869 5.675C20 6.018 20 6.418 20 7.218V12Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
</svg>
);

/* Label 03 — the Neuron atom, 24x24 on a 2 stroke. */
export const GlyphNeuron = ({ className }: Props) => (
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <path d="M12 12H12.01M15.54 15.536C10.85 20.222 5.47 22.438 3.51 20.485C1.56 18.533 3.78 13.151 8.46 8.465C13.15 3.778 18.53 1.562 20.48 3.515C22.44 5.467 20.22 10.849 15.54 15.536ZM15.54 8.464C20.22 13.151 22.44 18.533 20.48 20.485C18.53 22.438 13.15 20.222 8.46 15.535C3.78 10.849 1.56 5.467 3.51 3.515C5.47 1.562 10.85 3.778 15.54 8.464ZM12.5 12C12.5 12.276 12.28 12.5 12 12.5C11.72 12.5 11.5 12.276 11.5 12C11.5 11.724 11.72 11.5 12 11.5C12.28 11.5 12.5 11.724 12.5 12Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
</svg>
);

/* Label 04 — two figures, 24x24 on a 2 stroke. */
export const GlyphPeople = ({ className }: Props) => (
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <path d="M22 21V19C22 17.136 20.725 15.57 19 15.126M15.5 3.291C16.966 3.884 18 5.321 18 7C18 8.679 16.966 10.116 15.5 10.709M17 21C17 19.136 17 18.204 16.696 17.469C16.29 16.489 15.511 15.711 14.531 15.305C13.796 15 12.864 15 11 15H8C6.136 15 5.204 15 4.469 15.305C3.489 15.711 2.71 16.489 2.304 17.469C2 18.204 2 19.136 2 21M13.5 7C13.5 9.209 11.709 11 9.5 11C7.291 11 5.5 9.209 5.5 7C5.5 4.791 7.291 3 9.5 3C11.709 3 13.5 4.791 13.5 7Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
</svg>
);

/* Policy row mark — a page with lines, 20x20 on a 1.67 stroke. */
export const GlyphDocument = ({ className }: Props) => (
<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <path d="M11.667 1.891V5.333C11.667 5.8 11.667 6.034 11.758 6.212C11.838 6.369 11.966 6.496 12.122 6.576C12.301 6.667 12.534 6.667 13.001 6.667H16.443M11.667 14.167H6.667M13.334 10.833H6.667M16.667 8.324V14.333C16.667 15.734 16.667 16.434 16.395 16.968C16.155 17.439 15.773 17.821 15.302 18.061C14.768 18.333 14.067 18.333 12.667 18.333H7.334C5.934 18.333 5.234 18.333 4.699 18.061C4.229 17.821 3.846 17.439 3.606 16.968C3.334 16.434 3.334 15.734 3.334 14.333V5.667C3.334 4.267 3.334 3.567 3.606 3.032C3.846 2.561 4.229 2.179 4.699 1.939C5.234 1.667 5.934 1.667 7.334 1.667H10.01C10.622 1.667 10.928 1.667 11.215 1.736C11.47 1.797 11.714 1.898 11.938 2.035C12.19 2.19 12.407 2.406 12.839 2.838L15.496 5.495C15.928 5.928 16.144 6.144 16.299 6.396C16.436 6.62 16.537 6.864 16.598 7.119C16.667 7.406 16.667 7.712 16.667 8.324Z" stroke="currentColor" strokeWidth="1.67" strokeLinecap="round" strokeLinejoin="round"/>
</svg>
);
