/* Generated by tools/design/gen_trust.mjs from public/trust-security/Frame 2147226132.svg. Do not hand-edit. */

type Props = { className?: string };

/* Shield with a tick, in gradient plates; design box x 948.9..1279.1, y 90..472. */
export const Shield = ({ className }: Props) => (
<svg width="330.176" height="381.902" viewBox="948.914 90.049 330.176 381.902" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint0_linear_151_2943" x1="1092.25" y1="341.187" x2="1172.68" y2="249.419" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint1_linear_151_2943" x1="1226.46" y1="174.252" x2="1129.6" y2="281.144" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint2_linear_151_2943" x1="1030.97" y1="90.0494" x2="1030.97" y2="242.51" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint3_linear_151_2943" x1="1021.71" y1="201.839" x2="1021.71" y2="471.951" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint4_linear_151_2943" x1="1197.03" y1="201.839" x2="1197.03" y2="471.951" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint5_linear_151_2943" x1="1206.29" y1="90.0494" x2="1206.29" y2="242.51" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
  </defs>
  <path opacity="0.8" d="M1167.91 274.324L1100.4 351.614L1036.51 283.405L1068.3 253.681L1099.31 286.779L1135.14 245.683L1167.91 274.324Z" fill="url(#paint0_linear_151_2943)"/>
  <path opacity="0.8" d="M1170.28 205.429L1203.01 234.13L1148.9 296.113L1116.17 267.411L1170.28 205.429Z" fill="url(#paint1_linear_151_2943)"/>
  <path opacity="0.8" d="M1114 132.036L988.914 171.932V242.51H948.914V142.706L1114 90.0494V132.036Z" fill="url(#paint2_linear_151_2943)"/>
  <path opacity="0.8" d="M988.914 271.26C988.914 320.022 1016.97 393.194 1114 429.596V471.951C989.424 431.617 948.914 338.2 948.914 271.26V201.839H988.914V271.26Z" fill="url(#paint3_linear_151_2943)"/>
  <path opacity="0.8" d="M1239.09 271.26C1239.09 320.022 1211.03 393.194 1114 429.596V471.951C1238.58 431.617 1279.09 338.2 1279.09 271.26V201.839H1239.09V271.26Z" fill="url(#paint4_linear_151_2943)"/>
  <path opacity="0.8" d="M1114 132.036L1239.09 171.932V242.51H1279.09V142.706L1114 90.0494V132.036Z" fill="url(#paint5_linear_151_2943)"/>
</svg>
);
