/* Generated by tools/design/gen_trust.mjs from public/trust-security/Section-1.svg. Do not hand-edit. */

type Props = { className?: string };

/* Four isometric plates; design box x 487.8..952.2, y 328..845. */
export const LayerStack = ({ className }: Props) => (
<svg width="464.484" height="516.977" viewBox="487.758 328 464.484 516.977" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint0_linear_151_3636" x1="952.242" y1="759.594" x2="721.241" y2="700.981" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
<linearGradient id="paint1_linear_151_3636" x1="487.758" y1="764.294" x2="720" y2="704.53" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint2_linear_151_3636" x1="952.242" y1="757.414" x2="720" y2="817.179" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint3_linear_151_3636" x1="487.758" y1="762.115" x2="718.759" y2="820.728" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
<linearGradient id="paint4_linear_151_3636" x1="952.242" y1="643.35" x2="721.241" y2="584.737" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint5_linear_151_3636" x1="487.758" y1="648.05" x2="720" y2="588.286" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint6_linear_151_3636" x1="952.242" y1="641.17" x2="720" y2="700.935" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint7_linear_151_3636" x1="487.758" y1="645.871" x2="718.759" y2="704.484" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint8_linear_151_3636" x1="952.242" y1="527.106" x2="721.241" y2="468.493" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
<linearGradient id="paint9_linear_151_3636" x1="487.758" y1="531.806" x2="720" y2="472.042" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint10_linear_151_3636" x1="952.242" y1="524.926" x2="720" y2="584.691" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint11_linear_151_3636" x1="487.758" y1="529.627" x2="718.759" y2="588.24" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
<linearGradient id="paint12_linear_151_3636" x1="952.242" y1="410.861" x2="721.241" y2="352.249" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint13_linear_151_3636" x1="487.758" y1="415.562" x2="720" y2="355.798" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint14_linear_151_3636" x1="952.242" y1="408.682" x2="720" y2="468.447" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint15_linear_151_3636" x1="487.758" y1="413.383" x2="718.759" y2="471.996" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
  </defs>
  <path opacity="0.8" d="M720 732.028L952.242 788.459V733.164L720 676.732V732.028Z" fill="url(#paint0_linear_151_3636)"/>
  <path opacity="0.8" d="M720 732.028L487.758 788.459V733.164L720 676.732V732.028Z" fill="url(#paint1_linear_151_3636)"/>
  <path opacity="0.8" d="M720 789.681L952.242 733.25V788.545L720 844.977V789.681Z" fill="url(#paint2_linear_151_3636)"/>
  <path opacity="0.8" d="M720 789.681L487.758 733.25V788.545L720 844.977V789.681Z" fill="url(#paint3_linear_151_3636)"/>
  <path opacity="0.8" d="M720 615.784L952.242 672.215V616.919L720 560.488V615.784Z" fill="url(#paint4_linear_151_3636)"/>
  <path opacity="0.8" d="M720 615.784L487.758 672.215V616.919L720 560.488V615.784Z" fill="url(#paint5_linear_151_3636)"/>
  <path opacity="0.8" d="M720 673.437L952.242 617.006V672.301L720 728.732V673.437Z" fill="url(#paint6_linear_151_3636)"/>
  <path opacity="0.8" d="M720 673.437L487.758 617.006V672.301L720 728.732V673.437Z" fill="url(#paint7_linear_151_3636)"/>
  <path opacity="0.8" d="M720 499.54L952.242 555.971V500.675L720 444.244V499.54Z" fill="url(#paint8_linear_151_3636)"/>
  <path opacity="0.8" d="M720 499.54L487.758 555.971V500.675L720 444.244V499.54Z" fill="url(#paint9_linear_151_3636)"/>
  <path opacity="0.8" d="M720 557.193L952.242 500.761V556.057L720 612.488V557.193Z" fill="url(#paint10_linear_151_3636)"/>
  <path opacity="0.8" d="M720 557.193L487.758 500.761V556.057L720 612.488V557.193Z" fill="url(#paint11_linear_151_3636)"/>
  <path opacity="0.8" d="M720 383.296L952.242 439.727V384.431L720 328V383.296Z" fill="url(#paint12_linear_151_3636)"/>
  <path opacity="0.8" d="M720 383.296L487.758 439.727V384.431L720 328V383.296Z" fill="url(#paint13_linear_151_3636)"/>
  <path opacity="0.8" d="M720 440.948L952.242 384.517V439.813L720 496.244V440.948Z" fill="url(#paint14_linear_151_3636)"/>
  <path opacity="0.8" d="M720 440.948L487.758 384.517V439.813L720 496.244V440.948Z" fill="url(#paint15_linear_151_3636)"/>
</svg>
);

/* Label leader line — dot on the stack side; design box x 962.7..1001, y 408.6..419.2. */
export const Connector = ({ className }: Props) => (
<svg width="38.333" height="10.666" viewBox="962.667 408.557 38.333 10.666" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <path d="M1000 414.89H1001V412.89H1000V413.89V414.89ZM962.667 413.89C962.667 416.835 965.054 419.223 968 419.223C970.946 419.223 973.333 416.835 973.333 413.89C973.333 410.944 970.946 408.557 968 408.557C965.054 408.557 962.667 410.944 962.667 413.89ZM1000 413.89V412.89H968V413.89V414.89H1000V413.89Z" fill="#D5D7DA"/>
</svg>
);
