/* Generated by tools/design/gen_contact.mjs from public/contact/Frame 21472261322.svg. Do not hand-edit. */

type Props = { className?: string };

/* Navy -> pale blade off the top-right corner; design box x 1170.12..1639.28, y -45..311.7. */
export const BladeTopRight = ({ className }: Props) => (
<svg width="469.16" height="356.7" viewBox="1170.12 -45 469.16 356.7" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint0_linear_158_6725" x1="1207.46" y1="262.674" x2="1634" y2="74.7121" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
  </defs>
  <path opacity="0.8" d="M1549.8 -45C1576.06 -23.648 1606.35 -0.295235 1639.28 24.0026C1539.91 107.442 1374.54 223.933 1226.23 311.7L1170.12 216.875C1305.03 137.038 1454.2 32.7527 1549.8 -45Z" fill="url(#paint0_linear_158_6725)"/>
</svg>
);

/* Blue -> pale blade off the bottom-left corner; design box x -198.887..270.273, y 579..935.7. */
export const BladeBottomLeft = ({ className }: Props) => (
<svg width="469.16" height="356.7" viewBox="-198.887 579 469.16 356.7" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint1_linear_158_6725" x1="-154.883" y1="895.2" x2="270.724" y2="711.01" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
  </defs>
  <path opacity="0.8" d="M-109.412 935.7C-135.665 914.348 -165.958 890.995 -198.887 866.697C-99.5164 783.258 65.8461 666.767 214.159 579L270.273 673.825C135.361 753.662 -13.813 857.947 -109.412 935.7Z" fill="url(#paint1_linear_158_6725)"/>
</svg>
);
