/* Generated by tools/design/gen_career.mjs from public/carrers/Frame 2147226133.svg. Do not hand-edit. */

type Props = { className?: string };

/* Briefcase in gradient plates; design box x 876..1236, y 69..413. */
export const Briefcase = ({ className }: Props) => (
<svg width="360" height="344" viewBox="876 69 360 344" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint0_linear_132_4021" x1="876.5" y1="305.346" x2="1193" y2="305.346" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint1_linear_132_4021" x1="1030" y1="207.5" x2="1070.5" y2="242" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
<linearGradient id="paint2_linear_132_4021" x1="970.5" y1="128.913" x2="1135.5" y2="128.913" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint3_linear_132_4021" x1="969.873" y1="320.5" x2="969.873" y2="128.5" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint4_linear_132_4021" x1="1211.5" y1="131" x2="1211.5" y2="325" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
  </defs>
  <path opacity="0.8" d="M916 221V373H1196V221H1236V413H876V221H916Z" fill="url(#paint0_linear_132_4021)"/>
  <circle opacity="0.8" cx="1054" cy="225" r="24" fill="url(#paint1_linear_132_4021)"/>
  <path opacity="0.8" d="M1138 168H1098V109H1009V168H969V69H1138V168Z" fill="url(#paint2_linear_132_4021)"/>
  <path opacity="0.8" d="M1056 168H916V220.941C928.655 241.983 972.536 284 1056 284V324C952.644 324 894.308 268.392 878 234.717L876 230.588V128H1056V168Z" fill="url(#paint3_linear_132_4021)"/>
  <path opacity="0.8" d="M1236 128V230.588L1234 234.717C1217.72 268.333 1160.42 324 1056 324V284C1140.33 284 1183.41 242.045 1196 220.958V168H1056V128H1236Z" fill="url(#paint4_linear_132_4021)"/>
</svg>
);
