/* Generated by tools/design/gen_career.mjs from public/carrers/Section-2.svg. Do not hand-edit. */

type Props = { className?: string };

/* Step 1 numeral; design box x 175.5..218.5, y 299..401. */
export const NumberOne = ({ className }: Props) => (
<svg width="43" height="102" viewBox="175.5 299 43 102" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint0_linear_135_2798" x1="209.5" y1="401" x2="209.5" y2="343" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
<linearGradient id="paint1_linear_135_2798" x1="209.5" y1="299" x2="209.5" y2="365" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint2_linear_135_2798" x1="175.5" y1="323.448" x2="220.438" y2="300.484" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
  </defs>
  <rect opacity="0.8" x="200.5" y="343" width="18" height="58" fill="url(#paint0_linear_135_2798)"/>
  <rect opacity="0.8" x="200.5" y="299" width="18" height="66" fill="url(#paint1_linear_135_2798)"/>
  <path opacity="0.8" d="M218.5 299V309.401L175.5 334.228V313.442L200.516 299H218.5Z" fill="url(#paint2_linear_135_2798)"/>
</svg>
);

/* Step 2 numeral; design box x 570.8..639.2, y 299.5..400.5. */
export const NumberTwo = ({ className }: Props) => (
<svg width="68.436" height="100.968" viewBox="570.781 299.516 68.436 100.968" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint3_linear_135_2798" x1="571.217" y1="391.484" x2="639.217" y2="391.484" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint4_linear_135_2798" x1="562.54" y1="409.354" x2="621.052" y2="350.842" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint5_linear_135_2798" x1="572.387" y1="400.484" x2="623.127" y2="351.986" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
<linearGradient id="paint6_linear_135_2798" x1="570.781" y1="333.245" x2="637.74" y2="333.245" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
  </defs>
  <path opacity="0.8" d="M639.217 400.484H571.217V387.948L576.681 382.484H639.217V400.484Z" fill="url(#paint3_linear_135_2798)"/>
  <path d="M627.416 357.206L584.138 400.484H571.217V387.95L614.688 344.479L627.416 357.206Z" fill="url(#paint4_linear_135_2798)"/>
  <path d="M627.416 357.206L584.138 400.484H571.217V387.95L614.688 344.479L627.416 357.206Z" fill="url(#paint5_linear_135_2798)"/>
  <path opacity="0.8" d="M604.24 299.516C622.742 299.516 637.74 314.514 637.74 333.016C637.74 342.524 633.778 351.106 627.415 357.204L627.417 357.206L613.881 370.742L601.153 358.014L614.685 344.481C617.795 341.647 619.74 337.556 619.74 333.016C619.74 324.455 612.801 317.516 604.24 317.516C596.237 317.516 589.652 323.581 588.828 331.365H570.781C571.642 313.63 586.292 299.516 604.24 299.516Z" fill="url(#paint6_linear_135_2798)"/>
</svg>
);

/* Step 3 numeral; design box x 976.9..1049.1, y 297.6..402.4. */
export const NumberThree = ({ className }: Props) => (
<svg width="72.184" height="104.858" viewBox="976.906 297.571 72.184 104.858" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint7_linear_135_2798" x1="1027.92" y1="341.665" x2="1027.92" y2="402.429" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint8_linear_135_2798" x1="1006.75" y1="318.271" x2="1047.59" y2="326.114" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint9_linear_135_2798" x1="976.906" y1="392.524" x2="1014.19" y2="377.083" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint10_linear_135_2798" x1="976.906" y1="312.109" x2="1020.59" y2="312.109" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
  </defs>
  <path opacity="0.8" d="M1018.71 341.665L1019.5 341.677C1035.91 342.092 1049.09 355.531 1049.09 372.048C1049.09 388.565 1035.91 402.003 1019.5 402.419L1018.71 402.429H1006.75V385.886H1018.71C1026.35 385.886 1032.55 379.69 1032.55 372.048C1032.55 364.405 1026.35 358.209 1018.71 358.209H1007.32V341.665H1018.71Z" fill="url(#paint7_linear_135_2798)"/>
  <path opacity="0.8" d="M1018.71 358.335L1019.5 358.324C1035.91 357.908 1049.09 344.469 1049.09 327.952C1049.09 311.436 1035.91 297.997 1019.5 297.581L1018.71 297.571H1006.75V314.114H1018.71C1026.35 314.114 1032.55 320.31 1032.55 327.952C1032.55 335.595 1026.35 341.792 1018.71 341.792H1007.32V358.335H1018.71Z" fill="url(#paint8_linear_135_2798)"/>
  <path opacity="0.8" d="M993.481 373.353C994.139 380.383 1000.06 385.886 1007.26 385.886H1020.59V402.429H1007.26C990.916 402.429 977.59 389.526 976.906 373.353H993.481Z" fill="url(#paint9_linear_135_2798)"/>
  <path opacity="0.8" d="M993.481 326.647C994.139 319.617 1000.06 314.114 1007.26 314.114H1020.59V297.571H1007.26C990.916 297.572 977.59 310.474 976.906 326.647H993.481Z" fill="url(#paint10_linear_135_2798)"/>
</svg>
);
