/* Generated by tools/design/gen_career.mjs from public/carrers/Section.svg. Do not hand-edit. */

type Props = { className?: string };

/* Card 1 — target; design box x 157.3..331.1, y 541.3..715.1. */
export const IconMission = ({ className }: Props) => (
<svg width="173.731" height="173.73" viewBox="157.349 541.349 173.731 173.73" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint0_linear_132_4429" x1="296.881" y1="676.147" x2="203.974" y2="574.955" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
<linearGradient id="paint1_linear_132_4429" x1="304.576" y1="679.106" x2="195.691" y2="573.772" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint2_linear_132_4429" x1="244.5" y1="596.542" x2="244.5" y2="543.989" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint3_linear_132_4429" x1="329.43" y1="628" x2="275.906" y2="628" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint4_linear_132_4429" x1="159" y1="628" x2="212.524" y2="628" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint5_linear_132_4429" x1="244.5" y1="659.903" x2="244.5" y2="712.456" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
  </defs>
  <path opacity="0.8" d="M329.429 628.214C329.429 645.068 324.431 661.543 315.067 675.557C305.704 689.57 292.395 700.492 276.824 706.942C261.254 713.392 244.12 715.079 227.59 711.791C211.06 708.503 195.876 700.387 183.959 688.47C172.041 676.552 163.925 661.369 160.637 644.839C157.349 628.309 159.037 611.175 165.487 595.604C171.936 580.033 182.858 566.725 196.872 557.361C210.885 547.998 227.361 543 244.214 543V571.973C233.091 571.973 222.217 575.271 212.968 581.451C203.719 587.631 196.511 596.415 192.254 606.692C187.997 616.968 186.883 628.277 189.054 639.186C191.224 650.096 196.58 660.118 204.446 667.983C212.311 675.849 222.332 681.205 233.242 683.375C244.152 685.545 255.46 684.431 265.737 680.175C276.014 675.918 284.797 668.709 290.977 659.46C297.157 650.212 300.456 639.338 300.456 628.214H329.429Z" fill="url(#paint0_linear_132_4429)"/>
  <path opacity="0.8" d="M159.001 628.214C159.001 611.36 163.999 594.885 173.362 580.872C182.726 566.858 196.034 555.936 211.605 549.487C227.176 543.037 244.31 541.349 260.84 544.637C277.37 547.925 292.554 556.041 304.471 567.959C316.388 579.876 324.504 595.06 327.792 611.59C331.08 628.12 329.393 645.254 322.943 660.824C316.493 676.395 305.571 689.704 291.558 699.067C277.544 708.431 261.069 713.429 244.215 713.429V684.456C255.339 684.456 266.213 681.157 275.461 674.977C284.71 668.797 291.919 660.014 296.176 649.737C300.432 639.46 301.546 628.152 299.376 617.242C297.206 606.332 291.85 596.311 283.984 588.446C276.119 580.58 266.097 575.224 255.188 573.053C244.278 570.883 232.969 571.997 222.693 576.254C212.416 580.511 203.632 587.719 197.452 596.968C191.272 606.217 187.974 617.091 187.974 628.214H159.001Z" fill="url(#paint1_linear_132_4429)"/>
  <path opacity="0.8" d="M232 543.988C232 543.988 237.133 543.016 243.937 543.016C251.237 543.016 257 543.988 257 543.988V596.54H232V543.988Z" fill="url(#paint2_linear_132_4429)"/>
  <path opacity="0.8" d="M328.458 615.5C328.458 615.5 329.43 620.633 329.43 627.437C329.43 634.737 328.458 640.5 328.458 640.5L275.906 640.5L275.906 615.5L328.458 615.5Z" fill="url(#paint3_linear_132_4429)"/>
  <path opacity="0.8" d="M159.972 615.5C159.972 615.5 159 620.633 159 627.437C159 634.737 159.972 640.5 159.972 640.5L212.524 640.5L212.524 615.5L159.972 615.5Z" fill="url(#paint4_linear_132_4429)"/>
  <path opacity="0.8" d="M232 712.457C232 712.457 237.133 713.429 243.937 713.429C251.237 713.429 257 712.457 257 712.457V659.904H232V712.457Z" fill="url(#paint5_linear_132_4429)"/>
</svg>
);

/* Card 2 — map pin; design box x 569.3..730, y 537..718.4. */
export const IconFlexible = ({ className }: Props) => (
<svg width="160.709" height="181.418" viewBox="569.333 537 160.709 181.418" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint6_linear_132_4429" x1="670.447" y1="537" x2="760.724" y2="636.546" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint7_linear_132_4429" x1="645.835" y1="718.418" x2="734.58" y2="617.234" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint8_linear_132_4429" x1="663.624" y1="633.35" x2="630.723" y2="618.171" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
  </defs>
  <path opacity="0.8" d="M649.688 537C694.388 537 730.042 574.177 730.042 619.306C730.042 651.882 709.744 676.396 691.688 691.873C682.479 699.766 673.327 705.774 666.501 709.805C663.521 711.564 660.956 712.959 658.99 713.987L659.058 714.134L654.834 716.063L654.825 716.068L654.815 716.072L654.762 716.098L654.754 716.101L654.736 716.109L654.731 716.111H654.729L654.729 716.112C654.727 716.114 654.707 716.122 654.688 716.131L649.688 718.417L649.688 718.416V691.546C650.996 690.834 652.52 689.981 654.208 688.984C660.181 685.457 668.095 680.249 675.952 673.515C692.023 659.74 705.863 641.345 705.863 619.306C705.863 586.885 680.399 561.18 649.688 561.18H649.688V537Z" fill="url(#paint6_linear_132_4429)"/>
  <path d="M649.687 537.001C604.986 537.001 569.333 574.178 569.333 619.307C569.333 651.883 589.63 676.397 607.687 691.874C616.896 699.767 626.048 705.775 632.874 709.806C635.854 711.565 638.419 712.96 640.385 713.988L640.317 714.135L644.541 716.064L644.55 716.069L644.56 716.073L644.613 716.099L644.621 716.102L644.639 716.11L644.644 716.112H644.646V716.113C644.649 716.115 644.669 716.123 644.688 716.132L649.687 718.418L649.688 718.417V691.547C648.379 690.835 646.855 689.982 645.167 688.985C639.194 685.458 631.279 680.25 623.422 673.516C607.351 659.741 593.512 641.345 593.512 619.307C593.512 586.886 618.976 561.181 649.687 561.181H649.688V537.001H649.687Z" fill="url(#paint7_linear_132_4429)"/>
  <circle cx="649.689" cy="618.692" r="20.0565" fill="url(#paint8_linear_132_4429)"/>
</svg>
);

/* Card 3 — checked plate; design box x 974.7..1134.1, y 548..707.5. */
export const IconEquity = ({ className }: Props) => (
<svg width="159.474" height="159.479" viewBox="974.666 548 159.474 159.479" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint9_linear_132_4429" x1="1023.5" y1="707.468" x2="1023.5" y2="548" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint10_linear_132_4429" x1="1138.01" y1="658.777" x2="974.667" y2="658.777" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint11_linear_132_4429" x1="1047.41" y1="652.1" x2="1093.64" y2="599.411" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint12_linear_132_4429" x1="1124.76" y1="556.288" x2="1069.29" y2="617.763" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
  </defs>
  <path opacity="0.8" d="M1072.33 573.001H999.666V682.468L974.666 707.468V548H1072.33V573.001Z" fill="url(#paint9_linear_132_4429)"/>
  <path opacity="0.8" d="M1134.14 707.479H974.666V707.468L999.666 682.468V682.479H1109.14V610.075H1134.14V707.479Z" fill="url(#paint10_linear_132_4429)"/>
  <path opacity="0.8" d="M1097.51 606.166L1052.09 658.093L1015.41 618.895L1033.67 601.813L1051.46 620.834L1078.69 589.707L1097.51 606.166Z" fill="url(#paint11_linear_132_4429)"/>
  <path opacity="0.8" d="M1114.96 548.189L1133.79 564.63L1080.13 626.098L1061.3 609.655L1114.96 548.189Z" fill="url(#paint12_linear_132_4429)"/>
</svg>
);
