/* Generated by tools/design/gen_business.mjs from public/business/Section.svg. Do not hand-edit. */

type Props = { className?: string };

export const RiskRadarArt = ({ className }: Props) => (
<svg width="116.23" height="116.23" viewBox="202.9 901.09 116.23 116.23" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
<defs>
<linearGradient id="paint5_linear_123_3080" x1="296.251" y1="991.274" x2="234.091" y2="923.571" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
<linearGradient id="paint6_linear_123_3080" x1="301.399" y1="993.254" x2="228.548" y2="922.779" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint7_linear_123_3080" x1="270.162" y1="967.494" x2="253.326" y2="949.158" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
</defs>
<path opacity="0.8" d="M318.027 959.204C318.027 970.48 314.684 981.504 308.419 990.879C302.154 1000.26 293.25 1007.56 282.832 1011.88C272.414 1016.19 260.95 1017.32 249.891 1015.12C238.831 1012.92 228.672 1007.49 220.699 999.519C212.725 991.546 207.295 981.387 205.096 970.327C202.896 959.267 204.025 947.804 208.34 937.386C212.655 926.968 219.963 918.064 229.339 911.799C238.714 905.534 249.737 902.191 261.014 902.191V921.575C253.571 921.575 246.296 923.782 240.108 927.917C233.92 932.052 229.097 937.928 226.249 944.804C223.401 951.68 222.656 959.246 224.108 966.545C225.56 973.845 229.143 980.549 234.406 985.812C239.668 991.075 246.373 994.658 253.673 996.11C260.972 997.562 268.538 996.817 275.414 993.969C282.29 991.121 288.166 986.298 292.301 980.11C296.436 973.922 298.643 966.647 298.643 959.204H318.027Z" fill="url(#paint5_linear_123_3080)"/>
<path opacity="0.8" d="M204.001 959.204C204.001 947.928 207.345 936.905 213.609 927.529C219.874 918.153 228.779 910.846 239.196 906.53C249.614 902.215 261.078 901.086 272.137 903.286C283.197 905.486 293.356 910.916 301.329 918.889C309.303 926.863 314.733 937.022 316.933 948.081C319.133 959.141 318.004 970.605 313.688 981.022C309.373 991.44 302.066 1000.34 292.69 1006.61C283.314 1012.87 272.291 1016.22 261.015 1016.22V996.833C268.457 996.833 275.732 994.626 281.92 990.492C288.108 986.357 292.931 980.48 295.779 973.604C298.627 966.728 299.373 959.162 297.921 951.863C296.469 944.564 292.885 937.859 287.622 932.596C282.36 927.334 275.655 923.75 268.356 922.298C261.056 920.846 253.49 921.591 246.615 924.44C239.739 927.288 233.862 932.111 229.727 938.299C225.592 944.487 223.386 951.762 223.386 959.204H204.001Z" fill="url(#paint6_linear_123_3080)"/>
<circle opacity="0.8" cx="260.618" cy="958.808" r="15.4412" fill="url(#paint7_linear_123_3080)"/>
</svg>
);

export const DecisionMemoryArt = ({ className }: Props) => (
<svg width="122.92" height="122.93" viewBox="506 898 122.92 122.93" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
<defs>
<linearGradient id="paint8_linear_123_3080" x1="557.531" y1="1006.52" x2="559.158" y2="912.392" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint9_linear_123_3080" x1="617.3" y1="1008.77" x2="617.3" y2="912.391" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint10_linear_123_3080" x1="567.456" y1="975.412" x2="567.456" y2="943.513" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint11_linear_123_3080" x1="506" y1="947.014" x2="535.954" y2="947.014" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint12_linear_123_3080" x1="535.954" y1="971.911" x2="506" y2="971.911" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint13_linear_123_3080" x1="598.971" y1="947.014" x2="628.925" y2="947.014" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint14_linear_123_3080" x1="628.925" y1="971.911" x2="598.971" y2="971.911" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint15_linear_123_3080" x1="579.909" y1="898" x2="579.909" y2="927.954" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint16_linear_123_3080" x1="555.014" y1="927.954" x2="555.014" y2="898" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint17_linear_123_3080" x1="579.909" y1="990.971" x2="579.909" y2="1020.93" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint18_linear_123_3080" x1="555.014" y1="1020.93" x2="555.014" y2="990.971" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
</defs>
<path opacity="0.8" d="M598.949 927.952H535.945V990.956L520.385 1006.52V912.392H614.51L598.949 927.952Z" fill="url(#paint8_linear_123_3080)"/>
<path opacity="0.8" d="M535.942 990.957H598.949V927.951L614.51 912.391V1006.52H520.382L535.942 990.957Z" fill="url(#paint9_linear_123_3080)"/>
<rect opacity="0.8" x="551.896" y="943.513" width="31.1214" height="31.8995" fill="url(#paint10_linear_123_3080)"/>
<path opacity="0.8" d="M535.954 954.794H506V939.234H535.954V954.794Z" fill="url(#paint11_linear_123_3080)"/>
<path opacity="0.8" d="M535.954 979.692H506V964.131H535.954V979.692Z" fill="url(#paint12_linear_123_3080)"/>
<path opacity="0.8" d="M628.925 954.794H598.971V939.234H628.925V954.794Z" fill="url(#paint13_linear_123_3080)"/>
<path opacity="0.8" d="M628.925 979.692H598.971V964.131H628.925V979.692Z" fill="url(#paint14_linear_123_3080)"/>
<path opacity="0.8" d="M572.129 927.954L572.129 898L587.689 898L587.689 927.954L572.129 927.954Z" fill="url(#paint15_linear_123_3080)"/>
<path opacity="0.8" d="M547.233 927.954L547.233 898L562.794 898L562.794 927.954L547.233 927.954Z" fill="url(#paint16_linear_123_3080)"/>
<path opacity="0.8" d="M572.129 1020.93L572.129 990.971L587.689 990.971L587.689 1020.93L572.129 1020.93Z" fill="url(#paint17_linear_123_3080)"/>
<path opacity="0.8" d="M547.233 1020.93L547.233 990.971L562.794 990.971L562.794 1020.93L547.233 1020.93Z" fill="url(#paint18_linear_123_3080)"/>
</svg>
);

export const ContextArt = ({ className }: Props) => (
<svg width="102.88" height="120.22" viewBox="822 899 102.88 120.22" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
<defs>
<linearGradient id="paint19_linear_123_3080" x1="893.806" y1="960.797" x2="893.806" y2="899" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint20_linear_123_3080" x1="881.21" y1="899.023" x2="881.21" y2="1003.69" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint21_linear_123_3080" x1="873.441" y1="1019.22" x2="873.441" y2="899.022" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
</defs>
<path opacity="0.8" d="M878.371 899L878.37 945.27H924.768V960.797H862.844L862.845 899H878.371Z" fill="url(#paint19_linear_123_3080)"/>
<path opacity="0.8" d="M924.881 939.181L924.881 1019.19H837.538V1019.19H909.354L909.354 945.613L878.291 914.549L822.031 914.549V899.022L884.722 899.022L924.881 939.181Z" fill="url(#paint20_linear_123_3080)"/>
<path opacity="0.8" d="M837.54 914.549H837.526V1003.69H837.54V1003.69H924.882V1019.22H822V899.022H837.54V914.549Z" fill="url(#paint21_linear_123_3080)"/>
</svg>
);

export const AskAnythingArt = ({ className }: Props) => (
<svg width="124.19" height="122.88" viewBox="1117 898 124.19 122.88" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
<defs>
<linearGradient id="paint22_linear_123_3080" x1="1179.09" y1="1020.88" x2="1179.09" y2="898" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint23_linear_123_3080" x1="1188.46" y1="898.001" x2="1188.46" y2="978.613" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint24_linear_123_3080" x1="1201.92" y1="949.115" x2="1190.24" y2="936.394" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
<linearGradient id="paint25_linear_123_3080" x1="1155.14" y1="936.691" x2="1168.83" y2="949.933" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
</defs>
<path opacity="0.8" d="M1134.15 915.147H1134.15V989.799L1160.16 973.401H1224.04V973.391H1241.18V990.549H1165.12L1117 1020.88L1117 898H1134.15V915.147Z" fill="url(#paint22_linear_123_3080)"/>
<path opacity="0.8" d="M1241.19 990.547H1224.04L1224.04 915.147H1117V898H1241.18L1241.19 990.547Z" fill="url(#paint23_linear_123_3080)"/>
<circle opacity="0.8" cx="1195.3" cy="943.089" r="10.7125" fill="url(#paint24_linear_123_3080)"/>
<circle opacity="0.8" cx="1162.73" cy="943.089" r="10.7125" fill="url(#paint25_linear_123_3080)"/>
</svg>
);
