/* Generated by tools/design/gen_business.mjs from public/business/Frame 2147226132.svg. Do not hand-edit. */

type Props = { className?: string };

/* Four 80%-opacity gradient blades forming the star. */
export const HeroStar = ({ className }: Props) => (
<svg width="399" height="399" viewBox="882.5 58 399 399" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
<defs>
<linearGradient id="paint0_linear_123_1411" x1="1087.08" y1="433.541" x2="874.125" y2="287.428" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
<linearGradient id="paint1_linear_123_1411" x1="1064.99" y1="424.668" x2="1294.61" y2="347.736" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint2_linear_123_1411" x1="1269.35" y1="252.23" x2="1064.41" y2="85.5284" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint3_linear_123_1411" x1="899.725" y1="244.087" x2="1110.81" y2="173.153" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
</defs>
<path opacity="0.8" d="M882.5 221.771C1001.86 222.991 1098.25 320.129 1098.25 439.78C1098.25 445.576 1098.02 451.319 1097.58 457.001H1045.38C1045.96 451.34 1046.26 445.595 1046.26 439.78C1046.26 348.841 973.15 274.978 882.5 273.761V221.771Z" fill="url(#paint0_linear_123_1411)"/>
<path opacity="0.8" d="M1264.28 221.759C1270.08 221.759 1275.82 221.985 1281.5 222.429V274.628C1275.84 274.045 1270.1 273.746 1264.28 273.746C1172.58 273.747 1098.25 348.082 1098.25 439.78C1098.25 445.594 1098.55 451.339 1099.13 457H1046.93C1046.49 451.318 1046.26 445.575 1046.26 439.78C1046.26 319.37 1143.87 221.759 1264.28 221.759Z" fill="url(#paint1_linear_123_1411)"/>
<path opacity="0.8" d="M1098.91 58C1100.13 148.649 1173.99 221.759 1264.93 221.759C1270.52 221.759 1276.05 221.48 1281.5 220.94V273.125C1276.03 273.536 1270.5 273.746 1264.93 273.746C1145.28 273.746 1048.14 177.362 1046.92 58H1098.91Z" fill="url(#paint2_linear_123_1411)"/>
<path opacity="0.8" d="M1098.88 58C1097.67 176.821 1001.4 272.872 882.5 273.739V221.748C972.692 220.884 1045.68 148.109 1046.89 58H1098.88Z" fill="url(#paint3_linear_123_1411)"/>
</svg>
);
