/* Generated by tools/design/gen_business.mjs from public/business/Section.svg. Do not hand-edit. */

type Props = { className?: string };

/* Dashed source connectors, the graph edges and the platform slab. */
export const OntologyLines = ({ className }: Props) => (
<svg width="642" height="579" viewBox="682 1247.19 642 579" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
<defs>
<linearGradient id="paint35_linear_123_3080" x1="1006.97" y1="1583.25" x2="1006.97" y2="1759.45" gradientUnits="userSpaceOnUse">
<stop stopColor="white"/>
<stop offset="1" stopColor="white" stopOpacity="0"/>
</linearGradient>
<linearGradient id="paint36_linear_123_3080" x1="1006.97" y1="1759.45" x2="1006.97" y2="1791.62" gradientUnits="userSpaceOnUse">
<stop stopOpacity="0.5"/>
<stop offset="1"/>
</linearGradient>
<linearGradient id="paint37_linear_123_3080" x1="1006.97" y1="1759.45" x2="1006.97" y2="1816.65" gradientUnits="userSpaceOnUse">
<stop stopOpacity="0"/>
<stop offset="1"/>
</linearGradient>
</defs>
<path d="M1012 1424.33L1015.15 1656.51" stroke="#A4A7AE" strokeWidth="0.863845" strokeDasharray="3.46 3.46"/>
<path d="M901.859 1361.27L1018.48 1658.43" stroke="#A4A7AE" strokeWidth="0.863845" strokeDasharray="3.46 3.46"/>
<path d="M1095.36 1360.4L1015.89 1659.29" stroke="#A4A7AE" strokeWidth="0.863845" strokeDasharray="3.46 3.46"/>
<path d="M1184.34 1413.1L1014.16 1660.16" stroke="#A4A7AE" strokeWidth="0.863845" strokeDasharray="3.46 3.46"/>
<path d="M817.202 1416.55L1015.89 1656.7" stroke="#A4A7AE" strokeWidth="0.863845" strokeDasharray="3.46 3.46"/>
<path d="M773.146 1485.66L1015.02 1657.57" stroke="#A4A7AE" strokeWidth="0.863845" strokeDasharray="3.46 3.46"/>
<path d="M924.319 1485.66L1017.61 1659.29" stroke="#A4A7AE" strokeWidth="0.863845" strokeDasharray="3.46 3.46"/>
<path d="M1078.08 1485.66L1015.02 1658.43" stroke="#A4A7AE" strokeWidth="0.863845" strokeDasharray="3.46 3.46"/>
<path d="M1237.03 1488.25L1017.61 1656.7" stroke="#A4A7AE" strokeWidth="0.863845" strokeDasharray="3.46 3.46"/>
<path d="M1236.84 1583.25C1239.94 1583.25 1242.67 1585.32 1243.5 1588.3L1291.29 1759.45H722.646L770.438 1588.3C771.272 1585.32 773.993 1583.25 777.094 1583.25H1236.84Z" fill="white" fillOpacity="0.4" stroke="url(#paint35_linear_123_3080)" strokeWidth="0.863845"/>
<path d="M722.646 1759.45H1291.29V1784.71C1291.29 1788.53 1288.2 1791.62 1284.38 1791.62H729.557C725.741 1791.62 722.646 1788.53 722.646 1784.71V1759.45Z" fill="url(#paint36_linear_123_3080)" fillOpacity="0.06"/>
<path d="M1290.86 1759.88V1784.71C1290.86 1788.29 1287.96 1791.19 1284.38 1791.19H729.558C725.979 1791.19 723.078 1788.29 723.078 1784.71V1759.88H1290.86Z" stroke="url(#paint37_linear_123_3080)" strokeOpacity="0.1" strokeWidth="0.863845"/>
<path d="M849.131 1710.54L900.098 1720.04" stroke="#D5D7DA" strokeWidth="0.863845"/>
<path d="M934.652 1712.27L849.131 1636.68" stroke="#D5D7DA" strokeWidth="0.863845"/>
<path d="M1027.52 1698.01L948.042 1666.05" stroke="#D5D7DA" strokeWidth="0.863845"/>
<path d="M1067.25 1690.67L1062.93 1627.61" stroke="#D5D7DA" strokeWidth="0.863845"/>
<path d="M1110.88 1697.58L1185.6 1656.12" stroke="#D5D7DA" strokeWidth="0.863845"/>
<path d="M1035.72 1703.63L957.004 1724.68" stroke="#D5D7DA" strokeWidth="0.863845"/>
<path d="M1166.59 1718.31L1106.12 1703.19" stroke="#D5D7DA" strokeWidth="0.863845"/>
<path d="M1167.87 1633.43L1098.21 1616.52" stroke="#D5D7DA" strokeWidth="0.863845"/>
<path d="M919.135 1650.38L873.32 1627.18" stroke="#D5D7DA" strokeWidth="0.863845"/>
<path d="M1012.4 1618.97L970.502 1649.64" stroke="#D5D7DA" strokeWidth="0.863845"/>
</svg>
);
