/* Generated by tools/design/gen_about.mjs from public/about/Section-4.svg. Do not hand-edit. */

type Props = { className?: string };

/* Plus, built from eight gradient bars. */
export const IconDiversity = ({ className }: Props) => (
<svg width="121" height="121" viewBox="224 357 121 121" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint1_linear_123_1671" x1="267.5" y1="409" x2="267.5" y2="357" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint2_linear_123_1671" x1="8.49999" y1="52" x2="8.49999" y2="0" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint3_linear_123_1671" x1="8.49999" y1="52" x2="8.49999" y2="0" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint4_linear_123_1671" x1="318.5" y1="530" x2="318.5" y2="478" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint5_linear_123_1671" x1="232.5" y1="409" x2="232.5" y2="461" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
<linearGradient id="paint6_linear_123_1671" x1="8.5" y1="6.44878e-06" x2="8.50001" y2="52" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint7_linear_123_1671" x1="8.5" y1="6.44878e-06" x2="8.50001" y2="52" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint8_linear_123_1671" x1="353.5" y1="426" x2="353.5" y2="478" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
  </defs>
  <rect opacity="0.8" x="259" y="357" width="17" height="52" fill="url(#paint1_linear_123_1671)"/>
  <rect opacity="0.8" width="17" height="52" transform="matrix(1 0 0 -1 259 478)" fill="url(#paint2_linear_123_1671)"/>
  <rect opacity="0.8" width="17" height="52" transform="matrix(-1 0 0 1 310 357)" fill="url(#paint3_linear_123_1671)"/>
  <rect opacity="0.8" x="310" y="478" width="17" height="52" transform="rotate(180 310 478)" fill="url(#paint4_linear_123_1671)"/>
  <rect opacity="0.8" x="224" y="409" width="17" height="52" transform="rotate(-90 224 409)" fill="url(#paint5_linear_123_1671)"/>
  <rect opacity="0.8" width="17" height="52" transform="matrix(-4.37114e-08 1 1 4.37114e-08 224 426)" fill="url(#paint6_linear_123_1671)"/>
  <rect opacity="0.8" width="17" height="52" transform="matrix(4.37114e-08 -1 -1 -4.37114e-08 345 409)" fill="url(#paint7_linear_123_1671)"/>
  <rect opacity="0.8" x="345" y="426" width="17" height="52" transform="rotate(90 345 426)" fill="url(#paint8_linear_123_1671)"/>
</svg>
);

/* Equals sign. */
export const IconEquity = ({ className }: Props) => (
<svg width="119" height="120" viewBox="661 357 119 120" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint9_linear_123_1671" x1="8.5" y1="6.32477e-06" x2="8.50001" y2="51" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint10_linear_123_1671" x1="8.5" y1="6.32477e-06" x2="8.50001" y2="51" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint11_linear_123_1671" x1="788.5" y1="476" x2="788.5" y2="357" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint12_linear_123_1671" x1="788.5" y1="510" x2="788.5" y2="391" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint13_linear_123_1671" x1="8.49999" y1="51" x2="8.49999" y2="0" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint14_linear_123_1671" x1="8.49999" y1="51" x2="8.49999" y2="0" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint15_linear_123_1671" x1="788.5" y1="426" x2="788.5" y2="545" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint16_linear_123_1671" x1="788.5" y1="460" x2="788.5" y2="579" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
  </defs>
  <rect opacity="0.8" width="17" height="51" transform="matrix(-1 0 0 1 678 357)" fill="url(#paint9_linear_123_1671)"/>
  <rect opacity="0.8" width="17" height="51" transform="matrix(-1 0 0 1 780 357)" fill="url(#paint10_linear_123_1671)"/>
  <rect opacity="0.8" x="780" y="357" width="17" height="119" transform="rotate(90 780 357)" fill="url(#paint11_linear_123_1671)"/>
  <rect opacity="0.8" x="780" y="391" width="17" height="119" transform="rotate(90 780 391)" fill="url(#paint12_linear_123_1671)"/>
  <rect opacity="0.8" width="17" height="51" transform="matrix(-1 0 0 1 678 426)" fill="url(#paint13_linear_123_1671)"/>
  <rect opacity="0.8" width="17" height="51" transform="matrix(-1 0 0 1 780 426)" fill="url(#paint14_linear_123_1671)"/>
  <rect opacity="0.8" x="780" y="426" width="17" height="119" transform="rotate(90 780 426)" fill="url(#paint15_linear_123_1671)"/>
  <rect opacity="0.8" x="780" y="460" width="17" height="119" transform="rotate(90 780 460)" fill="url(#paint16_linear_123_1671)"/>
</svg>
);

/* Diamond with a diamond core. */
export const IconInclusion = ({ className }: Props) => (
<svg width="117.523" height="117.522" viewBox="1096.998 358 117.523 117.522" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint17_linear_123_1671" x1="1163.36" y1="441.101" x2="1163.36" y2="358" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint18_linear_123_1671" x1="1174.1" y1="464.781" x2="1174.1" y2="547.881" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
<linearGradient id="paint19_linear_123_1671" x1="1222.12" y1="416.761" x2="1222.12" y2="499.862" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint20_linear_123_1671" x1="1211.37" y1="489.12" x2="1211.37" y2="406.02" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint21_linear_123_1671" x1="1151.13" y1="416.761" x2="1151.13" y2="439.1" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
  </defs>
  <rect opacity="0.8" x="1155.76" y="358" width="15.1904" height="83.1005" transform="rotate(45 1155.76 358)" fill="url(#paint17_linear_123_1671)"/>
  <rect opacity="0.8" x="1166.5" y="464.781" width="15.1904" height="83.1005" transform="rotate(135 1166.5 464.781)" fill="url(#paint18_linear_123_1671)"/>
  <rect opacity="0.8" x="1214.52" y="416.761" width="15.1904" height="83.1005" transform="rotate(135 1214.52 416.761)" fill="url(#paint19_linear_123_1671)"/>
  <rect opacity="0.8" x="1203.78" y="406.02" width="15.1904" height="83.1005" transform="rotate(45 1203.78 406.02)" fill="url(#paint20_linear_123_1671)"/>
  <rect opacity="0.8" x="1139.96" y="416.761" width="22.3389" height="22.3389" transform="rotate(-45 1139.96 416.761)" fill="url(#paint21_linear_123_1671)"/>
</svg>
);
