/* Generated by tools/design/gen_about.mjs from public/about/Section.svg. Do not hand-edit. */

type Props = { className?: string };

/* Pale blade crossing the top-left corner; design box x -176.4..292.8, y 163..519.7. */
export const BladeTopLeft = ({ className }: Props) => (
<svg width="469.16" height="356.7" viewBox="-176.377 163 469.16 356.7" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint1_linear_123_1615" x1="-152.082" y1="198.573" x2="193.969" y2="539.073" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
  </defs>
  <path opacity="0.8" d="M-86.902 163C-113.155 184.352 -143.448 207.705 -176.377 232.003C-77.0066 315.442 88.3559 431.933 236.669 519.7L292.783 424.875C157.871 345.038 8.69678 240.753 -86.902 163Z" fill="url(#paint1_linear_123_1615)"/>
</svg>
);

/* Navy blade crossing the bottom-right corner; design box x 1205.4..1674.6, y 702.5..1059.2. */
export const BladeBottomRight = ({ className }: Props) => (
<svg width="469.16" height="356.705" viewBox="1205.42 702.525 469.16 356.705" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint0_linear_123_1615" x1="1637.23" y1="1010.2" x2="1210.7" y2="822.237" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
  </defs>
  <path opacity="0.8" d="M1294.89 702.525C1268.64 723.877 1238.35 747.23 1205.42 771.528C1304.79 854.967 1470.15 971.458 1618.47 1059.23L1674.58 964.401C1539.67 884.563 1390.49 780.278 1294.89 702.525Z" fill="url(#paint0_linear_123_1615)"/>
</svg>
);
