/* Generated by tools/design/gen_about.mjs from public/about/Frame 2147226133.svg. Do not hand-edit. */

type Props = { className?: string };

/* Torii gate in gradient blocks; design box x 808.1..1288, y 70.7..453.3. */
export const Torii = ({ className }: Props) => (
<svg width="479.888" height="382.556" viewBox="808.102 70.722 479.888 382.556" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint0_linear_123_1603" x1="940.522" y1="104.673" x2="940.522" y2="408.323" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint1_linear_123_1603" x1="1261.57" y1="238.359" x2="831.004" y2="238.359" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint2_linear_123_1603" x1="1156.21" y1="453.278" x2="1156.21" y2="104.672" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint3_linear_123_1603" x1="1046.28" y1="269.552" x2="1046.28" y2="116.722" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint4_linear_123_1603" x1="1287.99" y1="112.74" x2="808.102" y2="112.74" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
  </defs>
  <path opacity="0.8" d="M908.727 104.67L918.139 106.357C930.555 108.583 943.507 110.503 956.923 112.085L963.986 112.918V453.277H908.727V104.67Z" fill="url(#paint0_linear_123_1603)"/>
  <path opacity="0.8" d="M1261.57 269.552H831.004V214.292H1261.57V269.552Z" fill="url(#paint1_linear_123_1603)"/>
  <path opacity="0.8" d="M1183.84 104.672V453.278H1128.58V112.919L1135.65 112.086C1149.06 110.505 1162.01 108.585 1174.43 106.36L1183.84 104.672Z" fill="url(#paint2_linear_123_1603)"/>
  <path opacity="0.8" d="M1073.91 269.552H1018.65V116.722L1026.9 116.971C1033.3 117.164 1039.77 117.264 1046.29 117.264C1052.81 117.264 1059.27 117.164 1065.67 116.971L1073.91 116.722V269.552Z" fill="url(#paint3_linear_123_1603)"/>
  <path opacity="0.8" fillRule="evenodd" clipRule="evenodd" d="M1287.99 70.7224V131.487L1282.97 133.502C1222.83 157.635 1138.86 172.465 1046.29 172.465H1046.27L1042.08 172.454H1042.06C952.982 172.019 872.134 157.852 813.201 134.925L808.102 132.94V72.5427L819.388 77.6277C823.998 79.705 828.923 81.7652 834.168 83.7869C886.125 103.813 961.105 117.204 1046.29 117.204C1131.47 117.204 1206.45 103.813 1258.4 83.7869C1264.97 81.2557 1271.03 78.6706 1276.6 76.0623L1287.99 70.7224ZM1256.28 93.1345C1253.95 93.9892 1251.58 94.829 1249.17 95.657C1251.57 94.8336 1253.92 93.9989 1256.24 93.1492L1256.28 93.1345Z" fill="url(#paint4_linear_123_1603)"/>
</svg>
);
