/* Generated by tools/design/gen_about.mjs from public/about/Section-3.svg. Do not hand-edit. */
/* Generated by tools/design/gen_about.mjs from public/about/section1.svg. Do not hand-edit. */

type Props = { className?: string };

/* Checkerboard of gradient tiles behind the portrait, clipped to the card. */
export const LeaderMosaic = ({ className }: Props) => (
<svg width="389.333" height="460" viewBox="120 332 389.333 460" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint0_linear_123_2364" x1="199.123" y1="748.112" x2="43.623" y2="748.112" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint1_linear_123_2364" x1="155.5" y1="33.8622" x2="0" y2="33.8622" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint2_linear_123_2364" x1="43.623" y1="675.375" x2="199.123" y2="675.375" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint3_linear_123_2364" x1="9.58104e-07" y1="38.875" x2="155.5" y2="38.875" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint4_linear_123_2364" x1="38.875" y1="155.5" x2="38.875" y2="1.91621e-06" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint5_linear_123_2364" x1="160.248" y1="636.5" x2="160.248" y2="558.75" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint6_linear_123_2364" x1="315.623" y1="637" x2="315.623" y2="559" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint7_linear_123_2364" x1="199.123" y1="592.612" x2="43.623" y2="592.612" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint8_linear_123_2364" x1="78" y1="33.9711" x2="0" y2="33.9711" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint9_linear_123_2364" x1="237.998" y1="792" x2="237.998" y2="636.5" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint10_linear_123_2364" x1="393.498" y1="792" x2="393.498" y2="636.5" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
  </defs>
  <g opacity="0.5">
    <rect opacity="0.8" x="43.623" y="714.25" width="155.5" height="77.75" fill="url(#paint0_linear_123_2364)"/>
    <rect opacity="0.8" width="155.5" height="77.75" transform="matrix(-1 0 0 1 510.123 714.25)" fill="url(#paint1_linear_123_2364)"/>
    <rect opacity="0.8" x="43.623" y="636.5" width="155.5" height="77.75" fill="url(#paint2_linear_123_2364)"/>
    <rect opacity="0.8" width="155.5" height="77.75" transform="matrix(-1 0 0 1 510.123 636.5)" fill="url(#paint3_linear_123_2364)"/>
    <rect opacity="0.8" width="77.75" height="155.5" transform="matrix(-1 0 0 1 432.373 636.5)" fill="url(#paint4_linear_123_2364)"/>
    <rect opacity="0.8" x="121.373" y="558.75" width="77.75" height="77.75" fill="url(#paint5_linear_123_2364)"/>
    <rect opacity="0.8" x="276.623" y="559" width="78" height="78" fill="url(#paint6_linear_123_2364)"/>
    <g opacity="0.8">
      <rect x="43.623" y="558.75" width="155.5" height="77.75" fill="#D9D9D9"/>
      <rect x="43.623" y="558.75" width="155.5" height="77.75" fill="url(#paint7_linear_123_2364)"/>
    </g>
    <g opacity="0.8">
      <rect width="78" height="78" transform="matrix(-1 0 0 1 432.623 559)" fill="#D9D9D9"/>
      <rect width="78" height="78" transform="matrix(-1 0 0 1 432.623 559)" fill="url(#paint8_linear_123_2364)"/>
    </g>
    <rect opacity="0.8" x="199.123" y="636.5" width="77.75" height="155.5" fill="url(#paint9_linear_123_2364)"/>
    <rect opacity="0.8" x="354.623" y="636.5" width="77.75" height="155.5" transform="rotate(90 354.623 636.5)" fill="url(#paint10_linear_123_2364)"/>
  </g>
</svg>
);

/* The same checkerboard at the drawer's larger tile size, clipped to its photo frame. */
export const DrawerMosaic = ({ className }: Props) => (
<svg width="299" height="329.746" viewBox="1018.496 189 299 329.746" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint33_linear_123_2795" x1="1079.32" y1="485.012" x2="959.793" y2="485.012" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint34_linear_123_2795" x1="119.523" y1="26.0278" x2="0" y2="26.0278" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint35_linear_123_2795" x1="959.793" y1="429.103" x2="1079.32" y2="429.103" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint36_linear_123_2795" x1="7.36435e-07" y1="29.8808" x2="119.523" y2="29.8808" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint37_linear_123_2795" x1="1049.43" y1="518.745" x2="1049.43" y2="399.222" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint38_linear_123_2795" x1="29.8808" y1="119.523" x2="29.8808" y2="1.47287e-06" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint39_linear_123_2795" x1="1049.43" y1="399.223" x2="1049.43" y2="339.461" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint40_linear_123_2795" x1="29.8808" y1="119.523" x2="29.8808" y2="1.47287e-06" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint41_linear_123_2795" x1="1109.2" y1="399.222" x2="1109.2" y2="279.699" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint42_linear_123_2795" x1="1168.86" y1="399.607" x2="1168.86" y2="339.653" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint43_linear_123_2795" x1="1079.32" y1="365.489" x2="959.793" y2="365.489" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint44_linear_123_2795" x1="59.9537" y1="26.1115" x2="0" y2="26.1115" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint45_linear_123_2795" x1="1109.2" y1="518.745" x2="1109.2" y2="399.222" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint46_linear_123_2795" x1="1228.72" y1="518.745" x2="1228.72" y2="399.222" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint47_linear_123_2795" x1="1228.72" y1="458.984" x2="1228.72" y2="339.461" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint48_linear_123_2795" x1="1228.72" y1="578.507" x2="1228.72" y2="458.984" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
  </defs>
  <g opacity="0.5">
    <rect opacity="0.8" x="959.793" y="458.984" width="119.523" height="59.7616" fill="url(#paint33_linear_123_2795)"/>
    <rect opacity="0.8" width="119.523" height="59.7616" transform="matrix(-1 0 0 1 1318.36 458.984)" fill="url(#paint34_linear_123_2795)"/>
    <rect opacity="0.8" x="959.793" y="399.222" width="119.523" height="59.7616" fill="url(#paint35_linear_123_2795)"/>
    <rect opacity="0.8" width="119.523" height="59.7616" transform="matrix(-1 0 0 1 1318.36 399.222)" fill="url(#paint36_linear_123_2795)"/>
    <rect opacity="0.8" x="1019.55" y="399.222" width="59.7616" height="119.523" fill="url(#paint37_linear_123_2795)"/>
    <rect opacity="0.8" width="59.7616" height="119.523" transform="matrix(-1 0 0 1 1258.6 399.222)" fill="url(#paint38_linear_123_2795)"/>
    <rect opacity="0.8" x="1019.55" y="339.461" width="59.7616" height="59.7616" fill="url(#paint39_linear_123_2795)"/>
    <rect opacity="0.8" width="59.7616" height="119.523" transform="matrix(-1 0 0 1 1258.6 279.699)" fill="url(#paint40_linear_123_2795)"/>
    <g opacity="0.8">
      <rect x="1079.32" y="279.699" width="59.7616" height="119.523" fill="#D9D9D9"/>
      <rect x="1079.32" y="279.699" width="59.7616" height="119.523" fill="url(#paint41_linear_123_2795)"/>
    </g>
    <rect opacity="0.8" x="1138.88" y="339.653" width="59.9537" height="59.9537" fill="url(#paint42_linear_123_2795)"/>
    <g opacity="0.8">
      <rect x="959.793" y="339.461" width="119.523" height="59.7616" fill="#D9D9D9"/>
      <rect x="959.793" y="339.461" width="119.523" height="59.7616" fill="url(#paint43_linear_123_2795)"/>
    </g>
    <g opacity="0.8">
      <rect width="59.9537" height="59.9537" transform="matrix(-1 0 0 1 1258.79 339.653)" fill="#D9D9D9"/>
      <rect width="59.9537" height="59.9537" transform="matrix(-1 0 0 1 1258.79 339.653)" fill="url(#paint44_linear_123_2795)"/>
    </g>
    <rect opacity="0.8" x="1079.32" y="399.222" width="59.7616" height="119.523" fill="url(#paint45_linear_123_2795)"/>
    <rect opacity="0.8" x="1198.84" y="399.222" width="59.7616" height="119.523" transform="rotate(90 1198.84 399.222)" fill="url(#paint46_linear_123_2795)"/>
    <rect opacity="0.8" x="1198.84" y="339.461" width="59.7616" height="119.523" transform="rotate(90 1198.84 339.461)" fill="url(#paint47_linear_123_2795)"/>
    <g opacity="0.8">
      <rect x="1198.84" y="458.984" width="59.7616" height="119.523" transform="rotate(90 1198.84 458.984)" fill="#D9D9D9"/>
      <rect x="1198.84" y="458.984" width="59.7616" height="119.523" transform="rotate(90 1198.84 458.984)" fill="url(#paint48_linear_123_2795)"/>
    </g>
  </g>
</svg>
);
