/* Generated by tools/design/gen_about.mjs from public/about/Section-2.svg. Do not hand-edit. */

type Props = { className?: string };

/* Blurred top-left glow and the two gradient blades inside the navy card. */
export const PrinciplesCardArt = ({ className }: Props) => (
<svg width="533" height="496" viewBox="116 116 533 496" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<filter id="filter0_f_123_1638" x="-231.288" y="-277.352" width="815.426" height="815.426" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
<feFlood floodOpacity="0" result="BackgroundImageFix"/>
<feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
<feGaussianBlur stdDeviation="93.2982" result="effect1_foregroundBlur_123_1638"/>
</filter>
<linearGradient id="paint0_linear_123_1638" x1="955.215" y1="381.732" x2="466.222" y2="571.578" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint1_linear_123_1638" x1="407.663" y1="927.863" x2="413.243" y2="408.005" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
  </defs>
  <g filter="url(#filter0_f_123_1638)">
    <circle cx="176.425" cy="130.361" r="221.117" fill="#CAD4E6" fillOpacity="0.3"/>
  </g>
  <path opacity="0.8" d="M437.957 409.317C434.057 447.199 428.534 489.889 421.666 535.428C567.14 522.751 791.429 483.86 979.293 435.68L948.489 315.568C777.599 359.395 575.904 395.116 437.957 409.317Z" fill="url(#paint0_linear_123_1638)"/>
  <path opacity="0.8" d="M437.959 409.325C475.842 405.425 518.531 399.902 564.07 393.034C551.393 538.507 512.502 762.796 464.322 950.661L344.21 919.857C388.037 748.966 423.758 547.272 437.959 409.325Z" fill="url(#paint1_linear_123_1638)"/>
</svg>
);
