/* Generated by tools/design/gen_news.mjs from public/news/Frame 2147226133.svg. Do not hand-edit. */

type Props = { className?: string };

/* Megaphone in gradient shards; design box x 829..1244.1, y 37.4..361.9. */
export const Megaphone = ({ className }: Props) => (
<svg width="415.039" height="324.479" viewBox="829.041 37.434 415.039 324.479" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">
  <defs>
<linearGradient id="paint0_linear_123_6818" x1="964.502" y1="189.937" x2="844.158" y2="222.183" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint1_linear_123_6818" x1="960.436" y1="350.163" x2="930.5" y2="238.442" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint2_linear_123_6818" x1="1132.86" y1="220.532" x2="951.618" y2="269.096" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9E5FA"/>
<stop offset="1" stopColor="#0E3067"/>
</linearGradient>
<linearGradient id="paint3_linear_123_6818" x1="1107.8" y1="95.5178" x2="920.765" y2="145.635" gradientUnits="userSpaceOnUse">
<stop stopColor="#89B7D1"/>
<stop offset="1" stopColor="#D9EEFA"/>
</linearGradient>
<linearGradient id="paint4_linear_123_6818" x1="1157.16" y1="41.5187" x2="1171.98" y2="99.5316" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
<linearGradient id="paint5_linear_123_6818" x1="1203.93" y1="149.728" x2="1195.13" y2="116.886" gradientUnits="userSpaceOnUse">
<stop stopColor="#D9EEFA"/>
<stop offset="1" stopColor="#89B7D1"/>
</linearGradient>
<linearGradient id="paint6_linear_123_6818" x1="1193.02" y1="175.359" x2="1207.85" y2="233.372" gradientUnits="userSpaceOnUse">
<stop stopColor="#0E3067"/>
<stop offset="1" stopColor="#D9E5FA"/>
</linearGradient>
  </defs>
  <path opacity="0.8" fillRule="evenodd" clipRule="evenodd" d="M982.792 258.196L862.448 290.443L829.041 165.766L949.385 133.52L982.792 258.196ZM886.49 248.801L941.151 234.155L925.344 175.161L870.682 189.808L886.49 248.801Z" fill="url(#paint0_linear_123_6818)"/>
  <path opacity="0.8" d="M919.175 240.213L940.627 320.272L962.644 314.372L949.89 266.772L982.732 257.972L1004.29 338.414L916.586 361.913L886.334 249.012L919.175 240.213Z" fill="url(#paint1_linear_123_6818)"/>
  <path opacity="0.8" d="M1131.9 151.296C1141.27 186.267 1145.86 230.45 1117.21 278.045L1110.85 288.601L980.27 258.654L949.741 266.834L940.941 233.993L979.633 223.625L1093.86 249.822C1109.49 217.347 1106.37 187.375 1099.06 160.095L1131.9 151.296Z" fill="url(#paint2_linear_123_6818)"/>
  <path opacity="0.8" d="M1045.03 42.9083L1055.81 48.8726C1104.42 75.764 1122.54 116.321 1131.91 151.292L1099.07 160.092C1091.76 132.812 1079.48 105.298 1049.7 84.9871L963.879 164.788L925.528 175.064L916.728 142.222L946.916 134.134L1045.03 42.9083Z" fill="url(#paint3_linear_123_6818)"/>
  <path opacity="0.8" d="M1175.71 37.4343L1197.66 63.4011L1147.05 106.175L1125.1 80.2087L1175.71 37.4343Z" fill="url(#paint4_linear_123_6818)"/>
  <path opacity="0.8" d="M1244.08 138.969L1161.76 161.028L1152.96 128.186L1235.28 106.128L1244.08 138.969Z" fill="url(#paint5_linear_123_6818)"/>
  <g opacity="0.8">
    <path d="M1167.65 183.043L1232.86 194.785L1226.84 228.247L1161.63 216.506L1167.65 183.043Z" fill="#D9D9D9"/>
    <path d="M1167.65 183.043L1232.86 194.785L1226.84 228.247L1161.63 216.506L1167.65 183.043Z" fill="url(#paint6_linear_123_6818)"/>
  </g>
</svg>
);
