// Build the vector art for the career page from the Figma exports in `public/carrers`.
//   art -> React components in src/components/career/art/
//
// Every path, gradient, opacity and transform is copied verbatim out of the export, so
// what renders is what Figma drew. Change this generator, never the generated files.
//
// There are no photos in this set — all four exports are pure vector — so unlike
// `gen_about.mjs` / `gen_business.mjs` this only emits art. The tree walker comes from the
// shared `svgtree.mjs`, the same way `gen_news.mjs` takes it.
//
// What is art and what is chrome: the roles export's four pill strokes
// (`paint0..3_linear_135_2383`) are a gradient *border* on a live filter chip, so they
// stay CSS — see the comment in `RolesSection.tsx`. Everything selected here is drawing.
import { parse, flatten, component, writeModule } from './svgtree.mjs';
import fs from 'node:fs';
import path from 'node:path';

const SRC = 'public/carrers';
const ART_OUT = 'src/components/career/art';
fs.mkdirSync(ART_OUT, { recursive: true });

const HERO = 'Frame 2147226133.svg';
const WHY = 'Section.svg';
const PROCESS = 'Section-2.svg';

/* Figma's per-export id stem, so paint numbers can be written as ranges below. */
const STEM = { [HERO]: '132_4021', [WHY]: '132_4429', [PROCESS]: '135_2798' };

const load = (f) => fs.readFileSync(path.join(SRC, f), 'utf8');

const sources = {};
const all = {};
for (const f of [HERO, WHY, PROCESS]) {
  sources[f] = load(f);
  all[f] = flatten(parse(sources[f]));
}

/**
 * Nodes filled with any of the named paints, in the export's own document order so the
 * paint order stays Figma's rather than the order the numbers are listed in.
 */
const byPaint = (file, ...numbers) => {
  const ids = numbers.map((n) => `url(#paint${n}_linear_${STEM[file]})`);
  const hit = all[file].filter((n) => ids.includes(n.attrs.fill || ''));
  if (hit.length !== numbers.length)
    throw new Error(`${file}: wanted ${numbers.length} paints, matched ${hit.length}`);
  return hit;
};

const H = (f) => `/* Generated by tools/design/gen_career.mjs from public/carrers/${f}. Do not hand-edit. */`;

/* ── hero: the briefcase ────────────────────────────────────────────────── */
// Four gradient plates and the lock's circle. Design box x 876..1236, y 69..413 — it is
// anchored to the right of the 1440 canvas, not centred, so the component is placed by
// its right edge.
writeModule(ART_OUT, 'HeroArt.tsx', H(HERO), [
  component('Briefcase', sources[HERO], byPaint(HERO, 0, 1, 2, 3, 4), {
    note: 'Briefcase in gradient plates; design box x 876..1236, y 69..413.',
  }),
]);

/* ── why: the three card glyphs ─────────────────────────────────────────── */
// One per card, each sitting low in its 388.333x419 card rather than centred in it, so
// each is placed by its own measured offset. The first is two 172.1px rings offset by
// 1.7px plus four spokes; the second a pin over its dot; the third a plate and a tick.
writeModule(ART_OUT, 'WhyArt.tsx', H(WHY), [
  component('IconMission', sources[WHY], byPaint(WHY, 0, 1, 2, 3, 4, 5), {
    note: 'Card 1 — target; design box x 157.3..331.1, y 541.3..715.1.',
  }),
  component('IconFlexible', sources[WHY], byPaint(WHY, 6, 7, 8), {
    note: 'Card 2 — map pin; design box x 569.3..730, y 537..718.4.',
  }),
  component('IconEquity', sources[WHY], byPaint(WHY, 9, 10, 11, 12), {
    note: 'Card 3 — checked plate; design box x 974.7..1134.1, y 548..707.5.',
  }),
]);

/* ── process: the three numerals ────────────────────────────────────────── */
// Drawn shapes, not type: each is a stack of gradient shards, and none of the three shares
// a box with the others, so they are placed per column by their own offsets.
writeModule(ART_OUT, 'ProcessArt.tsx', H(PROCESS), [
  component('NumberOne', sources[PROCESS], byPaint(PROCESS, 0, 1, 2), {
    note: 'Step 1 numeral; design box x 175.5..218.5, y 299..401.',
  }),
  component('NumberTwo', sources[PROCESS], byPaint(PROCESS, 3, 4, 5, 6), {
    note: 'Step 2 numeral; design box x 570.8..639.2, y 299.5..400.5.',
  }),
  component('NumberThree', sources[PROCESS], byPaint(PROCESS, 7, 8, 9, 10), {
    note: 'Step 3 numeral; design box x 976.9..1049.1, y 297.6..402.4.',
  }),
]);
