// Build the vector art for the news page from the Figma exports in `public/news`.
//   art -> React components in src/components/news/art/
//
// Every path, gradient, opacity and transform is copied verbatim out of the export, so
// what renders is what Figma drew. `clip-path` groups are dropped, because the components
// are clipped by the DOM element they sit in rather than in the SVG.
// Change this generator, never the generated files.
//
// Unlike the other pages there are no photos to extract. The three rasters embedded in
// `Section.svg` are sample articles standing in for CMS rows — the built page loads those
// images from Supabase — so shipping them as assets would freeze the mock data into the
// build. The only bitmap-free thing the design owns is the placeholder that a row without
// an image falls back to, and that is pure vector.
import { parse, flatten, component, writeModule } from './svgtree.mjs';
import fs from 'node:fs';
import path from 'node:path';

const SRC = 'public/news';
const ART_OUT = 'src/components/news/art';
fs.mkdirSync(ART_OUT, { recursive: true });

const HERO = 'Frame 2147226133.svg';
const LIST = 'Section.svg';

const load = (f) => fs.readFileSync(path.join(SRC, f), 'utf8');

/* ── selection helpers ──────────────────────────────────────────────────── */
const trees = {};
const all = {};
for (const f of [HERO, LIST]) {
  // The list export inlines three multi-megabyte rasters. Nothing selected below refers
  // to them, so drop the base64 before parsing to keep this quick.
  const raw = load(f).replace(
    /(xlink:href|href)="data:image\/[a-z+]+;base64,[^"]*"/g,
    '$1="__IMG__"'
  );
  trees[f] = parse(raw);
  all[f] = flatten(trees[f]);
}
/** Nodes whose own markup fills with one of the named paint ids. */
const byPaint = (file, ids) =>
  all[file].filter((n) => ids.some((i) => (n.attrs.fill || '') === `url(#${i})`));
/** The n-th node matching a tag and attribute pair. */
const nth = (file, tag, attr, value, index = 0) =>
  all[file].filter((n) => n.tag === tag && n.attrs[attr] === value)[index];

const paints = (file, from, to) => {
  const stem = { [HERO]: '123_6818', [LIST]: '126_1764' }[file];
  const out = [];
  for (let i = from; i <= to; i++) out.push(`paint${i}_linear_${stem}`);
  return out;
};

const H = (f) => `/* Generated by tools/design/gen_news.mjs from public/news/${f}. Do not hand-edit. */`;

/* ── hero: the megaphone ────────────────────────────────────────────────── */
// Seven gradient shards plus a two-layer tail (a #D9D9D9 plate under a gradient, inside
// its own `<g opacity="0.8">`), so this is selected as a subtree rather than by paint
// alone. Design box x 829..1244.1, y 37.4..361.9 — it is anchored to the right of the
// 1440 canvas, not centred, so the component is placed by its right edge.
const hero = load(HERO);
writeModule(ART_OUT, 'HeroArt.tsx', H(HERO), [
  component(
    'Megaphone',
    hero,
    [...byPaint(HERO, paints(HERO, 0, 5)), nth(HERO, 'g', 'opacity', '0.8')],
    { note: 'Megaphone in gradient shards; design box x 829..1244.1, y 37.4..361.9.' }
  ),
]);

/* ── list: the placeholder a row without an image falls back to ─────────── */
// The whole card, taken from the first of the nine identical ones in the export: a navy
// plate, the white UNCHAIN lock-up, a blurred glow that overhangs the top edge, and four
// gradient blades that overhang the left and right. The viewBox is the card rect itself
// (120,686.07 384x243.07), so the component drops in as `inset-0` and the card's own
// rounding clips the overhang exactly as Figma's clip group did.
//
// The lock-up is inside the group, before the glow and blades, so it stays part of the
// artwork rather than being layered over it in the DOM — that keeps the paint order the
// export's. It is a logo, not copy, so it is vector here for the same reason it is in the
// navigation.
const list = load(LIST);
writeModule(ART_OUT, 'PlaceholderArt.tsx', H(LIST), [
  component('PlaceholderCard', list, nth(LIST, 'g', 'clip-path', 'url(#clip0_126_1764)'), {
    box: [120, 686.07, 504, 929.14],
    note: 'Fallback card art: navy plate, UNCHAIN lock-up, blurred glow and four blades.',
  }),
]);
