// Build the vector art for the trust & security page from the Figma exports in
// `public/trust-security`.
//   art -> React components in src/components/trust/art/
//
// Every path, gradient, opacity and transform is copied verbatim out of the export, so
// what renders is what Figma drew. Change this generator, never the generated files.
//
// All four exports are pure vector — there is no photography in this set — so like
// `gen_career.mjs` this only emits art, and takes the tree walker from the shared
// `svgtree.mjs`.
//
// What is art and what is chrome. The gradient shapes are drawing and come out here, as do
// the five stroked glyphs — not because they are art, but because each is one long path
// drawn at its place on the 1440 canvas and translating that by hand is what the rest of
// `icons.tsx` avoids by being short. What deliberately does *not* come out: the numerals
// 01..04 on the layer stack are live text, and every hairline in these exports is a border
// on a real box (the card outlines, the policy rules, the arrow buttons), so they are CSS.
import { parse, flatten, component, writeModule } from './svgtree.mjs';
import fs from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

const SRC = 'public/trust-security';
const ART_OUT = 'src/components/trust/art';
fs.mkdirSync(ART_OUT, { recursive: true });

const HERO = 'Frame 2147226132.svg';
const APPROACH = 'Section.svg';
const LAYERS = 'Section-1.svg';
const POLICIES = 'Section-2.svg';

/* Figma's per-export id stem, so paint numbers can be written as ranges below. */
const STEM = { [HERO]: '151_2943', [APPROACH]: '151_3464', [LAYERS]: '151_3636' };

const load = (f) => fs.readFileSync(path.join(SRC, f), 'utf8');

/* Glyph-translation checks, awaited at the end so a bad shift fails the run. */
const checks = [];

const sources = {};
const all = {};
for (const f of [HERO, APPROACH, LAYERS, POLICIES]) {
  sources[f] = load(f);
  all[f] = flatten(parse(sources[f]));
}

/**
 * Nodes filled with any of the named paints, in the export's own document order so the
 * paint order stays Figma's rather than the order the numbers are listed in.
 */
const byPaint = (file, ...numbers) => {
  const ids = numbers.map((n) => `url(#paint${n}_linear_${STEM[file]})`);
  const hit = all[file].filter((n) => ids.includes(n.attrs.fill || ''));
  if (hit.length !== numbers.length)
    throw new Error(`${file}: wanted ${numbers.length} paints, matched ${hit.length}`);
  return hit;
};

/** One of the four #D5D7DA line-and-dot connectors, picked by where its path starts. */
const byStart = (file, start) => {
  const hit = all[file].filter(
    (n) => n.attrs.fill === '#D5D7DA' && (n.attrs.d || '').startsWith(start)
  );
  if (hit.length !== 1) throw new Error(`${file}: connector at ${start} matched ${hit.length}`);
  return hit;
};

const H = (f) => `/* Generated by tools/design/gen_trust.mjs from public/trust-security/${f}. Do not hand-edit. */`;

/* ── stroked glyphs ─────────────────────────────────────────────────────── */
/**
 * Shift an absolute path's coordinates so a glyph drawn at its place on the 1440 page
 * becomes a 0,0-origin icon. Only whole coordinates move — `A`'s radii and flags and the
 * numbers inside `H`/`V` are handled per command, so nothing is scaled or rounded.
 */
const PAIRS = { M: 2, L: 2, T: 2, C: 6, S: 4, Q: 4 };
function translatePath(d, dx, dy) {
  if (/[a-z]/.test(d.replace(/[eE]/g, ''))) throw new Error('relative path commands');
  const r = (n) => String(Math.round(n * 1000) / 1000);
  return (d.match(/[A-Z][^A-Z]*/g) || [])
    .map((cmd) => {
      const op = cmd[0];
      const v = (cmd.slice(1).match(/-?\d*\.?\d+(?:e[-+]?\d+)?/gi) || []).map(Number);
      if (op === 'Z') return 'Z';
      if (op === 'H') return 'H' + v.map((n) => r(n - dx)).join(' ');
      if (op === 'V') return 'V' + v.map((n) => r(n - dy)).join(' ');
      if (op === 'A') {
        const out = [];
        for (let i = 0; i + 7 <= v.length; i += 7)
          out.push([v[i], v[i + 1], v[i + 2], v[i + 3], v[i + 4], v[i + 5] - dx, v[i + 6] - dy].map(r).join(' '));
        return 'A' + out.join(' ');
      }
      const step = PAIRS[op];
      if (!step) throw new Error(`unhandled path command ${op}`);
      const out = [];
      for (let i = 0; i + 2 <= v.length; i += 2) out.push(r(v[i] - dx) + ' ' + r(v[i + 1] - dy));
      return op + out.join(' ');
    })
    .join('');
}

/**
 * Prove a translated glyph is still the export's own drawing: render the result and the
 * same region of the export at 8x and require every subpixel to agree. Painted mid-grey
 * so a stroke that went missing cannot hide against the background.
 */
const Z = 8;
async function assertSameAsExport({ name, d, origin, size, strokeWidth, source }) {
  const frame = (viewBox, path) =>
    Buffer.from(
      `<svg xmlns="http://www.w3.org/2000/svg" width="${size * Z}" height="${size * Z}" ` +
        `viewBox="${viewBox}" fill="none"><rect x="${viewBox.split(' ')[0]}" y="${viewBox.split(' ')[1]}" ` +
        `width="${size}" height="${size}" fill="#888"/>${path}</svg>`
    );
  const stroke = (p) => `<path d="${p}" stroke="#fff" stroke-width="${strokeWidth}" ` +
    `stroke-linecap="round" stroke-linejoin="round" fill="none"/>`;
  const [mine, theirs] = await Promise.all(
    [
      frame(`0 0 ${size} ${size}`, stroke(d)),
      frame(`${origin[0]} ${origin[1]} ${size} ${size}`, stroke(source)),
    ].map((svg) => sharp(svg).raw().toBuffer())
  );
  // Coordinates are written to 3dp, so a rasteriser can disagree by a shade on an
  // antialiased edge. A real shift moves whole pixels, not shades — anything above 2/255
  // is one.
  let worst = 0;
  for (let i = 0; i < mine.length; i++) worst = Math.max(worst, Math.abs(mine[i] - theirs[i]));
  if (worst > 2)
    throw new Error(`${name}: translated glyph differs from the export by ${worst}/255 — not a rounding shade`);
  return worst;
}

/**
 * One stroked glyph as a currentColor icon. `origin` is the icon's own box on the page —
 * the export centres each of these in a circle, so the box is that circle's centre less
 * half the nominal icon size, not the ink box.
 */
const glyph = (file, { name, note, match, origin, size, strokeWidth }) => {
  const hit = all[file].filter((n) => (n.attrs.d || '').startsWith(match));
  if (hit.length !== 1) throw new Error(`${file}: glyph ${name} matched ${hit.length}`);
  const source = hit[0].attrs.d;
  const d = translatePath(source, origin[0], origin[1]);
  checks.push(assertSameAsExport({ name, d, origin, size, strokeWidth, source }));
  return {
    name,
    note,
    size: `${size}x${size}`,
    jsx:
      `<svg width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" fill="none" xmlns="http://www.w3.org/2000/svg" className={className} aria-hidden="true">\n` +
      `  <path d="${d}" stroke="currentColor" strokeWidth="${strokeWidth}" strokeLinecap="round" strokeLinejoin="round"/>\n` +
      `</svg>`,
  };
};

/* ── hero: the shield ───────────────────────────────────────────────────── */
// Six gradient plates: the two upper and two lower shield faces, plus the tick's two.
// Design box x 948.9..1279.1, y 90..472 — anchored to the right of the 1440 canvas rather
// than centred, so the component is placed by its right edge.
writeModule(ART_OUT, 'HeroArt.tsx', H(HERO), [
  component('Shield', sources[HERO], byPaint(HERO, 0, 1, 2, 3, 4, 5), {
    note: 'Shield with a tick, in gradient plates; design box x 948.9..1279.1, y 90..472.',
  }),
]);

/* ── our approach: the four card glyphs ─────────────────────────────────── */
// One per card. Each is centred on its card's 288px axis and on y=444, but they are
// different sizes, so each is placed by its own measured box rather than a shared one.
writeModule(ART_OUT, 'ApproachArt.tsx', H(APPROACH), [
  component('IconReadOnly', sources[APPROACH], byPaint(APPROACH, 0, 1, 2, 3, 4), {
    note: 'Card 1 — eye; design box x 203.4..324.6, y 395.8..492.2.',
  }),
  component('IconEncryption', sources[APPROACH], byPaint(APPROACH, 5, 6, 7, 8), {
    note: 'Card 2 — padlock; design box x 517.8..618.2, y 385.8..502.2.',
  }),
  component('IconNoTraining', sources[APPROACH], byPaint(APPROACH, 9, 10, 11), {
    note: 'Card 3 — barred ring; design box x 813.9..930.1, y 385.9..502.1.',
  }),
  component('IconHumanCall', sources[APPROACH], byPaint(APPROACH, 12, 13, 14), {
    note: 'Card 4 — person; design box x 1123..1229, y 388.8..499.2.',
  }),
]);

/* ── security layers: the isometric stack and its connector ─────────────── */
// Four plates of four gradient faces each, drawn bottom-up (04 first) so the stacking
// order is Figma's. The whole drawing is one component because the plates overlap: the
// front face of one sits over the back face of the one below it, and splitting them would
// lose that. The white numerals inside it are text, not art, and are not selected here.
//
// The connector is drawn once and mirrored in CSS — the four in the export are the same
// 38.8x12 line-and-dot, dot always on the stack's side.
writeModule(ART_OUT, 'LayersArt.tsx', H(LAYERS), [
  component('LayerStack', sources[LAYERS], byPaint(LAYERS, ...Array.from({ length: 16 }, (_, i) => i)), {
    note: 'Four isometric plates; design box x 487.8..952.2, y 328..845.',
  }),
  component('Connector', sources[LAYERS], byStart(LAYERS, 'M1000 414.89'), {
    note: 'Label leader line — dot on the stack side; design box x 962.7..1001, y 408.6..419.2.',
  }),
]);

/* ── the stroked glyphs ─────────────────────────────────────────────────── */
// The four label glyphs and the policy rows' document mark. These are icons, not drawing,
// and would normally be hand-copied into `icons.tsx` the way the rest of the site's are —
// but each is a single 1.5-2.5KB path drawn at its place on the 1440 canvas, so they are
// translated to a 0,0 origin here instead of by hand. Colour becomes currentColor so the
// caller tints them: white inside the black label discs, #414651 in the policy rows.
//
// Each label glyph is centred in a 50px disc, so its icon box is that centre less 12 —
// the discs are at 1024,388.89 / 144,502 / 1024,622 / 144,735.11 in the export. The
// document mark carries its own 20x20 clip at 128,371.
writeModule(ART_OUT, 'Glyphs.tsx', H(`{Section-1,Section-2}.svg`), [
  glyph(LAYERS, {
    name: 'GlyphTools',
    note: 'Label 01 — spanner and screwdriver, 24x24 on a 2 stroke.',
    match: 'M1043 407.89L1047.5 412.39',
    origin: [1037, 401.89],
    size: 24,
    strokeWidth: 2,
  }),
  glyph(LAYERS, {
    name: 'GlyphShieldTick',
    note: 'Label 02 — ticked shield, 24x24 on a 2 stroke.',
    match: 'M166 526.5L168 528.5',
    origin: [157, 515],
    size: 24,
    strokeWidth: 2,
  }),
  glyph(LAYERS, {
    name: 'GlyphNeuron',
    note: 'Label 03 — the Neuron atom, 24x24 on a 2 stroke.',
    match: 'M1049 647H1049.01',
    origin: [1037, 635],
    size: 24,
    strokeWidth: 2,
  }),
  glyph(LAYERS, {
    name: 'GlyphPeople',
    note: 'Label 04 — two figures, 24x24 on a 2 stroke.',
    match: 'M179 769.11V767.11',
    origin: [157, 748.11],
    size: 24,
    strokeWidth: 2,
  }),
  glyph(POLICIES, {
    name: 'GlyphDocument',
    note: 'Policy row mark — a page with lines, 20x20 on a 1.67 stroke.',
    match: 'M139.667 372.891V376.333',
    origin: [128, 371],
    size: 20,
    strokeWidth: 1.67,
  }),
]);

/* Nothing above writes a glyph without queueing its proof; fail the run if one differs. */
const worst = Math.max(...(await Promise.all(checks)));
console.log(
  `ok   ${checks.length} translated glyphs match the export at ${Z}x (worst subpixel ${worst}/255)`
);
