// Build the vector art for the contact page from the Figma export in `public/contact`.
//   art -> React components in src/components/contact/art/
//
// Every path, gradient and opacity is copied verbatim out of the export, so what renders
// is what Figma drew. The export's `clip-path` group is dropped — the components are
// clipped by the section they sit in rather than in the SVG, which is what lets both
// blades keep the overhang the design gives them.
// Change this generator, never the generated files.
//
// There are no photos on this page: the only art is the two gradient blades, one running
// off the top-right corner and one off the bottom-left. The two exports in the folder are
// the same drawing in its empty and filled states, so the art is taken from the empty one.
import { parse, flatten, component, writeModule } from './svgtree.mjs';
import fs from 'node:fs';
import path from 'node:path';

const SRC = 'public/contact';
const ART_OUT = 'src/components/contact/art';
fs.mkdirSync(ART_OUT, { recursive: true });

const FORM = 'Frame 21472261322.svg';
const STEM = '158_6725';

const src = fs.readFileSync(path.join(SRC, FORM), 'utf8');
const all = flatten(parse(src));
const byPaint = (id) => all.filter((n) => n.attrs.fill === `url(#paint${id}_linear_${STEM})`);

const H = `/* Generated by tools/design/gen_contact.mjs from public/contact/${FORM}. Do not hand-edit. */`;

/* ── the two gradient blades ────────────────────────────────────────────────
 * Both are the same 469.16 x 356.7 parallelogram at `opacity="0.8"`, drawn twice at
 * opposite corners and in opposite gradients. Each is emitted on its own so the page can
 * anchor them independently — the export puts the navy one at x 1170.12, y -45 (199.28px
 * past the right edge of the 1440 canvas and 45px above it) and the pale one at
 * x -198.887, y 579. */
writeModule(ART_OUT, 'HeroArt.tsx', H, [
  component('BladeTopRight', src, byPaint(0), {
    note: 'Navy -> pale blade off the top-right corner; design box x 1170.12..1639.28, y -45..311.7.',
  }),
  component('BladeBottomLeft', src, byPaint(1), {
    note: 'Blue -> pale blade off the bottom-left corner; design box x -198.887..270.273, y 579..935.7.',
  }),
]);
